## 반복문을  통한 데이터 프레임 접근하기 
- 2가지 원리를 이해하자
- 1. 반복문에 들어가는 값 , 2. 반복문을 통해서 나오는 값

In [4]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

- range는 range(10)이라는 숫자가 나온다.

- in 뒤에 range와 시퀀스객체에 따라 값이 달라진다.

In [2]:
a = ['사과','딸기','바나나','포도']

In [3]:
for i in a:
    print(i)

사과
딸기
바나나
포도

- 시퀀스 객체 등으로 range가 아닌 다른 것으로 끝나면 시퀀스객체 안에 값을 가지고 온다.


- 시퀀스객체를 range로는 표현 못하나?

In [5]:
for i in range(len(a)):
    print(a[i])

사과
딸기
바나나
포도

## 데이터프레임 접근하는 법
- 행과 열로 이루어 짐
- 2차원

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame({'과일':['사과','딸기','바나나','망고'],
                  '가격':[100,200,300,400]})

In [8]:
df

    과일   가격
0   사과  100
1   딸기  200
2  바나나  300
3   망고  400

In [9]:
df.columns #컬럼을 보는 법

Index(['과일', '가격'], dtype='object')

In [10]:
df.index #인덱스

RangeIndex(start=0, stop=4, step=1)

In [11]:
df['과일']

0     사과
1     딸기
2    바나나
3     망고
Name: 과일, dtype: object

In [12]:
df.iloc[1]

과일     딸기
가격    200
Name: 1, dtype: object

### 반복문으로 데이터프레임 접근하면 어떤 식일까?

In [13]:
for i in df:
    print(i)

과일
가격

In [14]:
df['과일']

0     사과
1     딸기
2    바나나
3     망고
Name: 과일, dtype: object

In [15]:
for i in df['과일']:
    print(i)

사과
딸기
바나나
망고

In [16]:
for i in range(len(df['과일'])):
    print(df.과일[i])

사과
딸기
바나나
망고

- 인덱스로 접근하기

In [20]:
for i in range(len(df)):
    print(df.과일.loc[i])
    
for i in range(len(df)):
    print(df.과일.iloc[i])

사과
딸기
바나나
망고
사과
딸기
바나나
망고

In [21]:
mpg = pd.read_csv('mpg.csv')

In [22]:
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [23]:
for i in mpg.model:
    print(i)

a4
a4
a4
a4
a4
a4
a4
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a4 quattro
a6 quattro
a6 quattro
a6 quattro
c1500 suburban 2wd
c1500 suburban 2wd
c1500 suburban 2wd
c1500 suburban 2wd
c1500 suburban 2wd
corvette
corvette
corvette
corvette
corvette
k1500 tahoe 4wd
k1500 tahoe 4wd
k1500 tahoe 4wd
k1500 tahoe 4wd
malibu
malibu
malibu
malibu
malibu
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
caravan 2wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
dakota pickup 4wd
durango 4wd
durango 4wd
durango 4wd
durango 4wd
durango 4wd
durango 4wd
durango 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
ram 1500 pickup 4wd
expedition 2wd
expedition 2wd
expedition 2wd
explorer 4wd
explorer 4wd
explorer 4wd
explorer 4wd
explorer 4wd
explorer 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
f150 pickup 4wd
mustang
mustang
mustang
mustang
mustang
mustang
mustang
mustang
mustang
civic
civic
civic
civic
civic
civic
civic
civic
civic
sonata
sonata
sonata
sonata
sonata
sonata
sonata
tiburon
tiburon
tiburon
tiburon
tiburon
tiburon
tiburon
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
grand cherokee 4wd
range rover
range rover
range rover
range rover
navigator 2wd
navigator 2wd
navigator 2wd
mountaineer 4wd
mountaineer 4wd
mountaineer 4wd
mountaineer 4wd
altima
altima
altima
altima
altima
altima
maxima
maxima
maxima
pathfinder 4wd
pathfinder 4wd
pathfinder 4wd
pathfinder 4wd
grand prix
grand prix
grand prix
grand prix
grand prix
forester awd
forester awd
forester awd
forester awd
forester awd
forester awd
impreza awd
impreza awd
impreza awd
impreza awd
impreza awd
impreza awd
impreza awd
impreza awd
4runner 4wd
4runner 4wd
4runner 4wd
4runner 4wd
4runner 4wd
4runner 4wd
camry
camry
camry
camry
camry
camry
camry
camry solara
camry solara
camry solara
camry solara
camry solara
camry solara
camry solara
corolla
corolla
corolla
corolla
corolla
land cruiser wagon 4wd
land cruiser wagon 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
toyota tacoma 4wd
gti
gti
gti
gti
gti
jetta
jetta
jetta
jetta
jetta
jetta
jetta
jetta
jetta
new beetle
new beetle
new beetle
new beetle
new beetle
new beetle
passat
passat
passat
passat
passat
passat
passat

- 두 개 이상 컬럼의 값을 가지고 올 순 없나? (model, year 를 가지고 오고 싶다.!)

In [27]:
for i, j, k in zip(mpg.model, mpg.year, mpg.cty):
    print(i,j,k)

a4 1999 18
a4 1999 21
a4 2008 20
a4 2008 21
a4 1999 16
a4 1999 18
a4 2008 18
a4 quattro 1999 18
a4 quattro 1999 16
a4 quattro 2008 20
a4 quattro 2008 19
a4 quattro 1999 15
a4 quattro 1999 17
a4 quattro 2008 17
a4 quattro 2008 15
a6 quattro 1999 15
a6 quattro 2008 17
a6 quattro 2008 16
c1500 suburban 2wd 2008 14
c1500 suburban 2wd 2008 11
c1500 suburban 2wd 2008 14
c1500 suburban 2wd 1999 13
c1500 suburban 2wd 2008 12
corvette 1999 16
corvette 1999 15
corvette 2008 16
corvette 2008 15
corvette 2008 15
k1500 tahoe 4wd 2008 14
k1500 tahoe 4wd 2008 11
k1500 tahoe 4wd 1999 11
k1500 tahoe 4wd 1999 14
malibu 1999 19
malibu 2008 22
malibu 1999 18
malibu 2008 18
malibu 2008 17
caravan 2wd 1999 18
caravan 2wd 1999 17
caravan 2wd 1999 16
caravan 2wd 1999 16
caravan 2wd 2008 17
caravan 2wd 2008 17
caravan 2wd 2008 11
caravan 2wd 1999 15
caravan 2wd 1999 15
caravan 2wd 2008 16
caravan 2wd 2008 16
dakota pickup 4wd 2008 15
dakota pickup 4wd 2008 14
dakota pickup 4wd 1999 13
dakota pickup 4wd 1999 14
dakota pickup 4wd 2008 14
dakota pickup 4wd 2008 14
dakota pickup 4wd 2008 9
dakota pickup 4wd 1999 11
dakota pickup 4wd 1999 11
durango 4wd 1999 13
durango 4wd 2008 13
durango 4wd 2008 9
durango 4wd 2008 13
durango 4wd 1999 11
durango 4wd 2008 13
durango 4wd 1999 11
ram 1500 pickup 4wd 2008 12
ram 1500 pickup 4wd 2008 9
ram 1500 pickup 4wd 2008 13
ram 1500 pickup 4wd 2008 13
ram 1500 pickup 4wd 2008 12
ram 1500 pickup 4wd 2008 9
ram 1500 pickup 4wd 1999 11
ram 1500 pickup 4wd 1999 11
ram 1500 pickup 4wd 2008 13
ram 1500 pickup 4wd 1999 11
expedition 2wd 1999 11
expedition 2wd 1999 11
expedition 2wd 2008 12
explorer 4wd 1999 14
explorer 4wd 1999 15
explorer 4wd 1999 14
explorer 4wd 2008 13
explorer 4wd 2008 13
explorer 4wd 1999 13
f150 pickup 4wd 1999 14
f150 pickup 4wd 1999 14
f150 pickup 4wd 1999 13
f150 pickup 4wd 1999 13
f150 pickup 4wd 2008 13
f150 pickup 4wd 1999 11
f150 pickup 4wd 2008 13
mustang 1999 18
mustang 1999 18
mustang 2008 17
mustang 2008 16
mustang 1999 15
mustang 1999 15
mustang 2008 15
mustang 2008 15
mustang 2008 14
civic 1999 28
civic 1999 24
civic 1999 25
civic 1999 23
civic 1999 24
civic 2008 26
civic 2008 25
civic 2008 24
civic 2008 21
sonata 1999 18
sonata 1999 18
sonata 2008 21
sonata 2008 21
sonata 1999 18
sonata 1999 18
sonata 2008 19
tiburon 1999 19
tiburon 1999 19
tiburon 2008 20
tiburon 2008 20
tiburon 2008 17
tiburon 2008 16
tiburon 2008 17
grand cherokee 4wd 2008 17
grand cherokee 4wd 2008 15
grand cherokee 4wd 1999 15
grand cherokee 4wd 1999 14
grand cherokee 4wd 2008 9
grand cherokee 4wd 2008 14
grand cherokee 4wd 2008 13
grand cherokee 4wd 2008 11
range rover 1999 11
range rover 2008 12
range rover 2008 12
range rover 1999 11
navigator 2wd 1999 11
navigator 2wd 1999 11
navigator 2wd 2008 12
mountaineer 4wd 1999 14
mountaineer 4wd 2008 13
mountaineer 4wd 2008 13
mountaineer 4wd 1999 13
altima 1999 21
altima 1999 19
altima 2008 23
altima 2008 23
altima 2008 19
altima 2008 19
maxima 1999 18
maxima 1999 19
maxima 2008 19
pathfinder 4wd 1999 14
pathfinder 4wd 1999 15
pathfinder 4wd 2008 14
pathfinder 4wd 2008 12
grand prix 1999 18
grand prix 1999 16
grand prix 1999 17
grand prix 2008 18
grand prix 2008 16
forester awd 1999 18
forester awd 1999 18
forester awd 2008 20
forester awd 2008 19
forester awd 2008 20
forester awd 2008 18
impreza awd 1999 21
impreza awd 1999 19
impreza awd 1999 19
impreza awd 1999 19
impreza awd 2008 20
impreza awd 2008 20
impreza awd 2008 19
impreza awd 2008 20
4runner 4wd 1999 15
4runner 4wd 1999 16
4runner 4wd 1999 15
4runner 4wd 1999 15
4runner 4wd 2008 16
4runner 4wd 2008 14
camry 1999 21
camry 1999 21
camry 2008 21
camry 2008 21
camry 1999 18
camry 1999 18
camry 2008 19
camry solara 1999 21
camry solara 1999 21
camry solara 2008 21
camry solara 2008 22
camry solara 1999 18
camry solara 1999 18
camry solara 2008 18
corolla 1999 24
corolla 1999 24
corolla 1999 26
corolla 2008 28
corolla 2008 26
land cruiser wagon 4wd 1999 11
land cruiser wagon 4wd 2008 13
toyota tacoma 4wd 1999 15
toyota tacoma 4wd 1999 16
toyota tacoma 4wd 2008 17
toyota tacoma 4wd 1999 15
toyota tacoma 4wd 1999 15
toyota tacoma 4wd 2008 15
toyota tacoma 4wd 2008 16
gti 1999 21
gti 1999 19
gti 2008 21
gti 2008 22
gti 1999 17
jetta 1999 33
jetta 1999 21
jetta 1999 19
jetta 2008 22
jetta 2008 21
jetta 2008 21
jetta 2008 21
jetta 1999 16
jetta 1999 17
new beetle 1999 35
new beetle 1999 29
new beetle 1999 21
new beetle 1999 19
new beetle 2008 20
new beetle 2008 20
passat 1999 21
passat 1999 18
passat 2008 19
passat 2008 21
passat 1999 16
passat 1999 18
passat 2008 17

- 해당 값을 리스트 안에 넣어서 추가분석하기 위해 정리하자!

In [30]:
a = []
b = []
c = []

for i, j, k in zip(mpg.model, mpg.year, mpg.cty):
    a.append(i)
    b.append(j)
    c.append(k)
    
print(a)

['a4', 'a4', 'a4', 'a4', 'a4', 'a4', 'a4', 'a4 quattro', 'a4 quattro', 'a4 quattro', 'a4 quattro', 'a4 quattro', 'a4 quattro', 'a4 quattro', 'a4 quattro', 'a6 quattro', 'a6 quattro', 'a6 quattro', 'c1500 suburban 2wd', 'c1500 suburban 2wd', 'c1500 suburban 2wd', 'c1500 suburban 2wd', 'c1500 suburban 2wd', 'corvette', 'corvette', 'corvette', 'corvette', 'corvette', 'k1500 tahoe 4wd', 'k1500 tahoe 4wd', 'k1500 tahoe 4wd', 'k1500 tahoe 4wd', 'malibu', 'malibu', 'malibu', 'malibu', 'malibu', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'caravan 2wd', 'dakota pickup 4wd', 'dakota pickup 4wd', 'dakota pickup 4wd', 'dakota pickup 4wd', 'dakota pickup 4wd', 'dakota pickup 4wd', 'dakota pickup 4wd', 'dakota pickup 4wd', 'dakota pickup 4wd', 'durango 4wd', 'durango 4wd', 'durango 4wd', 'durango 4wd', 'durango 4wd', 'durango 4wd', 'durango 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'ram 1500 pickup 4wd', 'expedition 2wd', 'expedition 2wd', 'expedition 2wd', 'explorer 4wd', 'explorer 4wd', 'explorer 4wd', 'explorer 4wd', 'explorer 4wd', 'explorer 4wd', 'f150 pickup 4wd', 'f150 pickup 4wd', 'f150 pickup 4wd', 'f150 pickup 4wd', 'f150 pickup 4wd', 'f150 pickup 4wd', 'f150 pickup 4wd', 'mustang', 'mustang', 'mustang', 'mustang', 'mustang', 'mustang', 'mustang', 'mustang', 'mustang', 'civic', 'civic', 'civic', 'civic', 'civic', 'civic', 'civic', 'civic', 'civic', 'sonata', 'sonata', 'sonata', 'sonata', 'sonata', 'sonata', 'sonata', 'tiburon', 'tiburon', 'tiburon', 'tiburon', 'tiburon', 'tiburon', 'tiburon', 'grand cherokee 4wd', 'grand cherokee 4wd', 'grand cherokee 4wd', 'grand cherokee 4wd', 'grand cherokee 4wd', 'grand cherokee 4wd', 'grand cherokee 4wd', 'grand cherokee 4wd', 'range rover', 'range rover', 'range rover', 'range rover', 'navigator 2wd', 'navigator 2wd', 'navigator 2wd', 'mountaineer 4wd', 'mountaineer 4wd', 'mountaineer 4wd', 'mountaineer 4wd', 'altima', 'altima', 'altima', 'altima', 'altima', 'altima', 'maxima', 'maxima', 'maxima', 'pathfinder 4wd', 'pathfinder 4wd', 'pathfinder 4wd', 'pathfinder 4wd', 'grand prix', 'grand prix', 'grand prix', 'grand prix', 'grand prix', 'forester awd', 'forester awd', 'forester awd', 'forester awd', 'forester awd', 'forester awd', 'impreza awd', 'impreza awd', 'impreza awd', 'impreza awd', 'impreza awd', 'impreza awd', 'impreza awd', 'impreza awd', '4runner 4wd', '4runner 4wd', '4runner 4wd', '4runner 4wd', '4runner 4wd', '4runner 4wd', 'camry', 'camry', 'camry', 'camry', 'camry', 'camry', 'camry', 'camry solara', 'camry solara', 'camry solara', 'camry solara', 'camry solara', 'camry solara', 'camry solara', 'corolla', 'corolla', 'corolla', 'corolla', 'corolla', 'land cruiser wagon 4wd', 'land cruiser wagon 4wd', 'toyota tacoma 4wd', 'toyota tacoma 4wd', 'toyota tacoma 4wd', 'toyota tacoma 4wd', 'toyota tacoma 4wd', 'toyota tacoma 4wd', 'toyota tacoma 4wd', 'gti', 'gti', 'gti', 'gti', 'gti', 'jetta', 'jetta', 'jetta', 'jetta', 'jetta', 'jetta', 'jetta', 'jetta', 'jetta', 'new beetle', 'new beetle', 'new beetle', 'new beetle', 'new beetle', 'new beetle', 'passat', 'passat', 'passat', 'passat', 'passat', 'passat', 'passat']

In [32]:
mpg.cty.mean()

16.858974358974358

In [31]:
#mpg데이터 중 model ,cty 그 중 cty가 16.8 이상 친구들만 반복문으로 가지고 오기!
#cty  16.8 이상 친구들은 어떻게 가지고 올까요?

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

- 수치형데이터를 if문으로 만들어서 조건을 걸었다.

In [33]:
for i, j in zip(mpg.model, mpg.cty):
    if j >= 16.8:
        print(i, j)

a4 18
a4 21
a4 20
a4 21
a4 18
a4 18
a4 quattro 18
a4 quattro 20
a4 quattro 19
a4 quattro 17
a4 quattro 17
a6 quattro 17
malibu 19
malibu 22
malibu 18
malibu 18
malibu 17
caravan 2wd 18
caravan 2wd 17
caravan 2wd 17
caravan 2wd 17
mustang 18
mustang 18
mustang 17
civic 28
civic 24
civic 25
civic 23
civic 24
civic 26
civic 25
civic 24
civic 21
sonata 18
sonata 18
sonata 21
sonata 21
sonata 18
sonata 18
sonata 19
tiburon 19
tiburon 19
tiburon 20
tiburon 20
tiburon 17
tiburon 17
grand cherokee 4wd 17
altima 21
altima 19
altima 23
altima 23
altima 19
altima 19
maxima 18
maxima 19
maxima 19
grand prix 18
grand prix 17
grand prix 18
forester awd 18
forester awd 18
forester awd 20
forester awd 19
forester awd 20
forester awd 18
impreza awd 21
impreza awd 19
impreza awd 19
impreza awd 19
impreza awd 20
impreza awd 20
impreza awd 19
impreza awd 20
camry 21
camry 21
camry 21
camry 21
camry 18
camry 18
camry 19
camry solara 21
camry solara 21
camry solara 21
camry solara 22
camry solara 18
camry solara 18
camry solara 18
corolla 24
corolla 24
corolla 26
corolla 28
corolla 26
toyota tacoma 4wd 17
gti 21
gti 19
gti 21
gti 22
gti 17
jetta 33
jetta 21
jetta 19
jetta 22
jetta 21
jetta 21
jetta 21
jetta 17
new beetle 35
new beetle 29
new beetle 21
new beetle 19
new beetle 20
new beetle 20
passat 21
passat 18
passat 19
passat 21
passat 18
passat 17

- 카테고리형 변수에 대해서 조건 문을 만들어 보자!

malibu mustang 이 두 개의 차만 가지고 오고 싶다.

In [36]:
car_wt= ['malibu','mustang']
car_cty = [18]
for i, j in zip(mpg.model, mpg.cty):
    if i in car_wt and j in car_cty:
        print(i,j)

malibu 18
malibu 18
mustang 18
mustang 18

### 반복문 제공되는 함수들
- iterows

In [43]:
for idx, row in mpg.iterrows(): #idx 인덱스, Row 전체 데이터프레임
    print(idx,row['cty'],row['model'])

0 18 a4
1 21 a4
2 20 a4
3 21 a4
4 16 a4
5 18 a4
6 18 a4
7 18 a4 quattro
8 16 a4 quattro
9 20 a4 quattro
10 19 a4 quattro
11 15 a4 quattro
12 17 a4 quattro
13 17 a4 quattro
14 15 a4 quattro
15 15 a6 quattro
16 17 a6 quattro
17 16 a6 quattro
18 14 c1500 suburban 2wd
19 11 c1500 suburban 2wd
20 14 c1500 suburban 2wd
21 13 c1500 suburban 2wd
22 12 c1500 suburban 2wd
23 16 corvette
24 15 corvette
25 16 corvette
26 15 corvette
27 15 corvette
28 14 k1500 tahoe 4wd
29 11 k1500 tahoe 4wd
30 11 k1500 tahoe 4wd
31 14 k1500 tahoe 4wd
32 19 malibu
33 22 malibu
34 18 malibu
35 18 malibu
36 17 malibu
37 18 caravan 2wd
38 17 caravan 2wd
39 16 caravan 2wd
40 16 caravan 2wd
41 17 caravan 2wd
42 17 caravan 2wd
43 11 caravan 2wd
44 15 caravan 2wd
45 15 caravan 2wd
46 16 caravan 2wd
47 16 caravan 2wd
48 15 dakota pickup 4wd
49 14 dakota pickup 4wd
50 13 dakota pickup 4wd
51 14 dakota pickup 4wd
52 14 dakota pickup 4wd
53 14 dakota pickup 4wd
54 9 dakota pickup 4wd
55 11 dakota pickup 4wd
56 11 dakota pickup 4wd
57 13 durango 4wd
58 13 durango 4wd
59 9 durango 4wd
60 13 durango 4wd
61 11 durango 4wd
62 13 durango 4wd
63 11 durango 4wd
64 12 ram 1500 pickup 4wd
65 9 ram 1500 pickup 4wd
66 13 ram 1500 pickup 4wd
67 13 ram 1500 pickup 4wd
68 12 ram 1500 pickup 4wd
69 9 ram 1500 pickup 4wd
70 11 ram 1500 pickup 4wd
71 11 ram 1500 pickup 4wd
72 13 ram 1500 pickup 4wd
73 11 ram 1500 pickup 4wd
74 11 expedition 2wd
75 11 expedition 2wd
76 12 expedition 2wd
77 14 explorer 4wd
78 15 explorer 4wd
79 14 explorer 4wd
80 13 explorer 4wd
81 13 explorer 4wd
82 13 explorer 4wd
83 14 f150 pickup 4wd
84 14 f150 pickup 4wd
85 13 f150 pickup 4wd
86 13 f150 pickup 4wd
87 13 f150 pickup 4wd
88 11 f150 pickup 4wd
89 13 f150 pickup 4wd
90 18 mustang
91 18 mustang
92 17 mustang
93 16 mustang
94 15 mustang
95 15 mustang
96 15 mustang
97 15 mustang
98 14 mustang
99 28 civic
100 24 civic
101 25 civic
102 23 civic
103 24 civic
104 26 civic
105 25 civic
106 24 civic
107 21 civic
108 18 sonata
109 18 sonata
110 21 sonata
111 21 sonata
112 18 sonata
113 18 sonata
114 19 sonata
115 19 tiburon
116 19 tiburon
117 20 tiburon
118 20 tiburon
119 17 tiburon
120 16 tiburon
121 17 tiburon
122 17 grand cherokee 4wd
123 15 grand cherokee 4wd
124 15 grand cherokee 4wd
125 14 grand cherokee 4wd
126 9 grand cherokee 4wd
127 14 grand cherokee 4wd
128 13 grand cherokee 4wd
129 11 grand cherokee 4wd
130 11 range rover
131 12 range rover
132 12 range rover
133 11 range rover
134 11 navigator 2wd
135 11 navigator 2wd
136 12 navigator 2wd
137 14 mountaineer 4wd
138 13 mountaineer 4wd
139 13 mountaineer 4wd
140 13 mountaineer 4wd
141 21 altima
142 19 altima
143 23 altima
144 23 altima
145 19 altima
146 19 altima
147 18 maxima
148 19 maxima
149 19 maxima
150 14 pathfinder 4wd
151 15 pathfinder 4wd
152 14 pathfinder 4wd
153 12 pathfinder 4wd
154 18 grand prix
155 16 grand prix
156 17 grand prix
157 18 grand prix
158 16 grand prix
159 18 forester awd
160 18 forester awd
161 20 forester awd
162 19 forester awd
163 20 forester awd
164 18 forester awd
165 21 impreza awd
166 19 impreza awd
167 19 impreza awd
168 19 impreza awd
169 20 impreza awd
170 20 impreza awd
171 19 impreza awd
172 20 impreza awd
173 15 4runner 4wd
174 16 4runner 4wd
175 15 4runner 4wd
176 15 4runner 4wd
177 16 4runner 4wd
178 14 4runner 4wd
179 21 camry
180 21 camry
181 21 camry
182 21 camry
183 18 camry
184 18 camry
185 19 camry
186 21 camry solara
187 21 camry solara
188 21 camry solara
189 22 camry solara
190 18 camry solara
191 18 camry solara
192 18 camry solara
193 24 corolla
194 24 corolla
195 26 corolla
196 28 corolla
197 26 corolla
198 11 land cruiser wagon 4wd
199 13 land cruiser wagon 4wd
200 15 toyota tacoma 4wd
201 16 toyota tacoma 4wd
202 17 toyota tacoma 4wd
203 15 toyota tacoma 4wd
204 15 toyota tacoma 4wd
205 15 toyota tacoma 4wd
206 16 toyota tacoma 4wd
207 21 gti
208 19 gti
209 21 gti
210 22 gti
211 17 gti
212 33 jetta
213 21 jetta
214 19 jetta
215 22 jetta
216 21 jetta
217 21 jetta
218 21 jetta
219 16 jetta
220 17 jetta
221 35 new beetle
222 29 new beetle
223 21 new beetle
224 19 new beetle
225 20 new beetle
226 20 new beetle
227 21 passat
228 18 passat
229 19 passat
230 21 passat
231 16 passat
232 18 passat
233 17 passat

- itertuples
- 첫 필드 인덱스, 나머지 열

In [45]:
for row in mpg.itertuples():
    print(row.model, row.cty)

a4 18
a4 21
a4 20
a4 21
a4 16
a4 18
a4 18
a4 quattro 18
a4 quattro 16
a4 quattro 20
a4 quattro 19
a4 quattro 15
a4 quattro 17
a4 quattro 17
a4 quattro 15
a6 quattro 15
a6 quattro 17
a6 quattro 16
c1500 suburban 2wd 14
c1500 suburban 2wd 11
c1500 suburban 2wd 14
c1500 suburban 2wd 13
c1500 suburban 2wd 12
corvette 16
corvette 15
corvette 16
corvette 15
corvette 15
k1500 tahoe 4wd 14
k1500 tahoe 4wd 11
k1500 tahoe 4wd 11
k1500 tahoe 4wd 14
malibu 19
malibu 22
malibu 18
malibu 18
malibu 17
caravan 2wd 18
caravan 2wd 17
caravan 2wd 16
caravan 2wd 16
caravan 2wd 17
caravan 2wd 17
caravan 2wd 11
caravan 2wd 15
caravan 2wd 15
caravan 2wd 16
caravan 2wd 16
dakota pickup 4wd 15
dakota pickup 4wd 14
dakota pickup 4wd 13
dakota pickup 4wd 14
dakota pickup 4wd 14
dakota pickup 4wd 14
dakota pickup 4wd 9
dakota pickup 4wd 11
dakota pickup 4wd 11
durango 4wd 13
durango 4wd 13
durango 4wd 9
durango 4wd 13
durango 4wd 11
durango 4wd 13
durango 4wd 11
ram 1500 pickup 4wd 12
ram 1500 pickup 4wd 9
ram 1500 pickup 4wd 13
ram 1500 pickup 4wd 13
ram 1500 pickup 4wd 12
ram 1500 pickup 4wd 9
ram 1500 pickup 4wd 11
ram 1500 pickup 4wd 11
ram 1500 pickup 4wd 13
ram 1500 pickup 4wd 11
expedition 2wd 11
expedition 2wd 11
expedition 2wd 12
explorer 4wd 14
explorer 4wd 15
explorer 4wd 14
explorer 4wd 13
explorer 4wd 13
explorer 4wd 13
f150 pickup 4wd 14
f150 pickup 4wd 14
f150 pickup 4wd 13
f150 pickup 4wd 13
f150 pickup 4wd 13
f150 pickup 4wd 11
f150 pickup 4wd 13
mustang 18
mustang 18
mustang 17
mustang 16
mustang 15
mustang 15
mustang 15
mustang 15
mustang 14
civic 28
civic 24
civic 25
civic 23
civic 24
civic 26
civic 25
civic 24
civic 21
sonata 18
sonata 18
sonata 21
sonata 21
sonata 18
sonata 18
sonata 19
tiburon 19
tiburon 19
tiburon 20
tiburon 20
tiburon 17
tiburon 16
tiburon 17
grand cherokee 4wd 17
grand cherokee 4wd 15
grand cherokee 4wd 15
grand cherokee 4wd 14
grand cherokee 4wd 9
grand cherokee 4wd 14
grand cherokee 4wd 13
grand cherokee 4wd 11
range rover 11
range rover 12
range rover 12
range rover 11
navigator 2wd 11
navigator 2wd 11
navigator 2wd 12
mountaineer 4wd 14
mountaineer 4wd 13
mountaineer 4wd 13
mountaineer 4wd 13
altima 21
altima 19
altima 23
altima 23
altima 19
altima 19
maxima 18
maxima 19
maxima 19
pathfinder 4wd 14
pathfinder 4wd 15
pathfinder 4wd 14
pathfinder 4wd 12
grand prix 18
grand prix 16
grand prix 17
grand prix 18
grand prix 16
forester awd 18
forester awd 18
forester awd 20
forester awd 19
forester awd 20
forester awd 18
impreza awd 21
impreza awd 19
impreza awd 19
impreza awd 19
impreza awd 20
impreza awd 20
impreza awd 19
impreza awd 20
4runner 4wd 15
4runner 4wd 16
4runner 4wd 15
4runner 4wd 15
4runner 4wd 16
4runner 4wd 14
camry 21
camry 21
camry 21
camry 21
camry 18
camry 18
camry 19
camry solara 21
camry solara 21
camry solara 21
camry solara 22
camry solara 18
camry solara 18
camry solara 18
corolla 24
corolla 24
corolla 26
corolla 28
corolla 26
land cruiser wagon 4wd 11
land cruiser wagon 4wd 13
toyota tacoma 4wd 15
toyota tacoma 4wd 16
toyota tacoma 4wd 17
toyota tacoma 4wd 15
toyota tacoma 4wd 15
toyota tacoma 4wd 15
toyota tacoma 4wd 16
gti 21
gti 19
gti 21
gti 22
gti 17
jetta 33
jetta 21
jetta 19
jetta 22
jetta 21
jetta 21
jetta 21
jetta 16
jetta 17
new beetle 35
new beetle 29
new beetle 21
new beetle 19
new beetle 20
new beetle 20
passat 21
passat 18
passat 19
passat 21
passat 16
passat 18
passat 17

In [46]:
for i in range(0,mpg.shape[0]):
    print(mpg.iloc[i])

manufacturer        audi
model                 a4
displ                1.8
year                1999
cyl                    4
trans           auto(l5)
drv                    f
cty                   18
hwy                   29
fl                     p
category         compact
Name: 0, dtype: object
manufacturer          audi
model                   a4
displ                  1.8
year                  1999
cyl                      4
trans           manual(m5)
drv                      f
cty                     21
hwy                     29
fl                       p
category           compact
Name: 1, dtype: object
manufacturer          audi
model                   a4
displ                  2.0
year                  2008
cyl                      4
trans           manual(m6)
drv                      f
cty                     20
hwy                     31
fl                       p
category           compact
Name: 2, dtype: object
manufacturer        audi
model                 a4
displ                2.0
year                2008
cyl                    4
trans           auto(av)
drv                    f
cty                   21
hwy                   30
fl                     p
category         compact
Name: 3, dtype: object
manufacturer        audi
model                 a4
displ                2.8
year                1999
cyl                    6
trans           auto(l5)
drv                    f
cty                   16
hwy                   26
fl                     p
category         compact
Name: 4, dtype: object
manufacturer          audi
model                   a4
displ                  2.8
year                  1999
cyl                      6
trans           manual(m5)
drv                      f
cty                     18
hwy                     26
fl                       p
category           compact
Name: 5, dtype: object
manufacturer        audi
model                 a4
displ                3.1
year                2008
cyl                    6
trans           auto(av)
drv                    f
cty                   18
hwy                   27
fl                     p
category         compact
Name: 6, dtype: object
manufacturer          audi
model           a4 quattro
displ                  1.8
year                  1999
cyl                      4
trans           manual(m5)
drv                      4
cty                     18
hwy                     26
fl                       p
category           compact
Name: 7, dtype: object
manufacturer          audi
model           a4 quattro
displ                  1.8
year                  1999
cyl                      4
trans             auto(l5)
drv                      4
cty                     16
hwy                     25
fl                       p
category           compact
Name: 8, dtype: object
manufacturer          audi
model           a4 quattro
displ                  2.0
year                  2008
cyl                      4
trans           manual(m6)
drv                      4
cty                     20
hwy                     28
fl                       p
category           compact
Name: 9, dtype: object
manufacturer          audi
model           a4 quattro
displ                  2.0
year                  2008
cyl                      4
trans             auto(s6)
drv                      4
cty                     19
hwy                     27
fl                       p
category           compact
Name: 10, dtype: object
manufacturer          audi
model           a4 quattro
displ                  2.8
year                  1999
cyl                      6
trans             auto(l5)
drv                      4
cty                     15
hwy                     25
fl                       p
category           compact
Name: 11, dtype: object
manufacturer          audi
model           a4 quattro
displ                  2.8
year                  1999
cyl                      6
trans           manual(m5)
drv                      4
cty                     17
hwy                     25
fl                       p
category           compact
Name: 12, dtype: object
manufacturer          audi
model           a4 quattro
displ                  3.1
year                  2008
cyl                      6
trans             auto(s6)
drv                      4
cty                     17
hwy                     25
fl                       p
category           compact
Name: 13, dtype: object
manufacturer          audi
model           a4 quattro
displ                  3.1
year                  2008
cyl                      6
trans           manual(m6)
drv                      4
cty                     15
hwy                     25
fl                       p
category           compact
Name: 14, dtype: object
manufacturer          audi
model           a6 quattro
displ                  2.8
year                  1999
cyl                      6
trans             auto(l5)
drv                      4
cty                     15
hwy                     24
fl                       p
category           midsize
Name: 15, dtype: object
manufacturer          audi
model           a6 quattro
displ                  3.1
year                  2008
cyl                      6
trans             auto(s6)
drv                      4
cty                     17
hwy                     25
fl                       p
category           midsize
Name: 16, dtype: object
manufacturer          audi
model           a6 quattro
displ                  4.2
year                  2008
cyl                      8
trans             auto(s6)
drv                      4
cty                     16
hwy                     23
fl                       p
category           midsize
Name: 17, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             14
hwy                             20
fl                               r
category                       suv
Name: 18, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             11
hwy                             15
fl                               e
category                       suv
Name: 19, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             14
hwy                             20
fl                               r
category                       suv
Name: 20, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.7
year                          1999
cyl                              8
trans                     auto(l4)
drv                              r
cty                             13
hwy                             17
fl                               r
category                       suv
Name: 21, dtype: object
manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          6.0
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             12
hwy                             17
fl                               r
category                       suv
Name: 22, dtype: object
manufacturer     chevrolet
model             corvette
displ                  5.7
year                  1999
cyl                      8
trans           manual(m6)
drv                      r
cty                     16
hwy                     26
fl                       p
category           2seater
Name: 23, dtype: object
manufacturer    chevrolet
model            corvette
displ                 5.7
year                 1999
cyl                     8
trans            auto(l4)
drv                     r
cty                    15
hwy                    23
fl                      p
category          2seater
Name: 24, dtype: object
manufacturer     chevrolet
model             corvette
displ                  6.2
year                  2008
cyl                      8
trans           manual(m6)
drv                      r
cty                     16
hwy                     26
fl                       p
category           2seater
Name: 25, dtype: object
manufacturer    chevrolet
model            corvette
displ                 6.2
year                 2008
cyl                     8
trans            auto(s6)
drv                     r
cty                    15
hwy                    25
fl                      p
category          2seater
Name: 26, dtype: object
manufacturer     chevrolet
model             corvette
displ                  7.0
year                  2008
cyl                      8
trans           manual(m6)
drv                      r
cty                     15
hwy                     24
fl                       p
category           2seater
Name: 27, dtype: object
manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.3
year                       2008
cyl                           8
trans                  auto(l4)
drv                           4
cty                          14
hwy                          19
fl                            r
category                    suv
Name: 28, dtype: object
manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.3
year                       2008
cyl                           8
trans                  auto(l4)
drv                           4
cty                          11
hwy                          14
fl                            e
category                    suv
Name: 29, dtype: object
manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.7
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          11
hwy                          15
fl                            r
category                    suv
Name: 30, dtype: object
manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       6.5
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          14
hwy                          17
fl                            d
category                    suv
Name: 31, dtype: object
manufacturer    chevrolet
model              malibu
displ                 2.4
year                 1999
cyl                     4
trans            auto(l4)
drv                     f
cty                    19
hwy                    27
fl                      r
category          midsize
Name: 32, dtype: object
manufacturer    chevrolet
model              malibu
displ                 2.4
year                 2008
cyl                     4
trans            auto(l4)
drv                     f
cty                    22
hwy                    30
fl                      r
category          midsize
Name: 33, dtype: object
manufacturer    chevrolet
model              malibu
displ                 3.1
year                 1999
cyl                     6
trans            auto(l4)
drv                     f
cty                    18
hwy                    26
fl                      r
category          midsize
Name: 34, dtype: object
manufacturer    chevrolet
model              malibu
displ                 3.5
year                 2008
cyl                     6
trans            auto(l4)
drv                     f
cty                    18
hwy                    29
fl                      r
category          midsize
Name: 35, dtype: object
manufacturer    chevrolet
model              malibu
displ                 3.6
year                 2008
cyl                     6
trans            auto(s6)
drv                     f
cty                    17
hwy                    26
fl                      r
category          midsize
Name: 36, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   2.4
year                   1999
cyl                       4
trans              auto(l3)
drv                       f
cty                      18
hwy                      24
fl                        r
category            minivan
Name: 37, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.0
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 38, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      16
hwy                      22
fl                        r
category            minivan
Name: 39, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      16
hwy                      22
fl                        r
category            minivan
Name: 40, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 41, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 42, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      11
hwy                      17
fl                        e
category            minivan
Name: 43, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      15
hwy                      22
fl                        r
category            minivan
Name: 44, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      15
hwy                      21
fl                        r
category            minivan
Name: 45, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   2008
cyl                       6
trans              auto(l6)
drv                       f
cty                      16
hwy                      23
fl                        r
category            minivan
Name: 46, dtype: object
manufacturer          dodge
model           caravan 2wd
displ                   4.0
year                   2008
cyl                       6
trans              auto(l6)
drv                       f
cty                      16
hwy                      23
fl                        r
category            minivan
Name: 47, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         3.7
year                         2008
cyl                             6
trans                  manual(m6)
drv                             4
cty                            15
hwy                            19
fl                              r
category                   pickup
Name: 48, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         3.7
year                         2008
cyl                             6
trans                    auto(l4)
drv                             4
cty                            14
hwy                            18
fl                              r
category                   pickup
Name: 49, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         3.9
year                         1999
cyl                             6
trans                    auto(l4)
drv                             4
cty                            13
hwy                            17
fl                              r
category                   pickup
Name: 50, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         3.9
year                         1999
cyl                             6
trans                  manual(m5)
drv                             4
cty                            14
hwy                            17
fl                              r
category                   pickup
Name: 51, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                            14
hwy                            19
fl                              r
category                   pickup
Name: 52, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                            14
hwy                            19
fl                              r
category                   pickup
Name: 53, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                             9
hwy                            12
fl                              e
category                   pickup
Name: 54, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         5.2
year                         1999
cyl                             8
trans                  manual(m5)
drv                             4
cty                            11
hwy                            17
fl                              r
category                   pickup
Name: 55, dtype: object
manufacturer                dodge
model           dakota pickup 4wd
displ                         5.2
year                         1999
cyl                             8
trans                    auto(l4)
drv                             4
cty                            11
hwy                            15
fl                              r
category                   pickup
Name: 56, dtype: object
manufacturer          dodge
model           durango 4wd
displ                   3.9
year                   1999
cyl                       6
trans              auto(l4)
drv                       4
cty                      13
hwy                      17
fl                        r
category                suv
Name: 57, dtype: object
manufacturer          dodge
model           durango 4wd

- 컬럼 기반으로 접근해 보기
- 컬럼의 데이터 타입에 따라 출력할 수 있다.

In [48]:
for i in mpg:
    print(i)

manufacturer
model
displ
year
cyl
trans
drv
cty
hwy
fl
category

In [49]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  234 non-null    object
 1   model         234 non-null    object
 2   displ         234 non-null    float64
 3   year          234 non-null    int64
 4   cyl           234 non-null    int64
 5   trans         234 non-null    object
 6   drv           234 non-null    object
 7   cty           234 non-null    int64
 8   hwy           234 non-null    int64
 9   fl            234 non-null    object
 10  category      234 non-null    object
dtypes: float64(1), int64(4), object(6)
memory usage: 20.2+ KB

In [53]:
for col in mpg.columns:
    df_coltp = str(mpg[col].dtype)
    if df_coltp =='object':
        print(col,'object')
    else:
        print(col,'else')

manufacturer object
model object
displ else
year else
cyl else
trans object
drv object
cty else
hwy else
fl object
category object

In [54]:
for col in mpg.columns:
    df_coltp = str(mpg[col].dtype)
    if df_coltp =='object':
        print(col, mpg[col].value_counts())
    else:
        print(col,mpg[col].describe())

manufacturer dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: manufacturer, dtype: int64
model caravan 2wd               11
ram 1500 pickup 4wd       10
civic                      9
jetta                      9
dakota pickup 4wd          9
mustang                    9
impreza awd                8
a4 quattro                 8
grand cherokee 4wd         8
a4                         7
toyota tacoma 4wd          7
camry solara               7
camry                      7
tiburon                    7
sonata                     7
passat                     7
f150 pickup 4wd            7
durango 4wd                7
explorer 4wd               6
new beetle                 6
altima                     6
4runner 4wd                6
forester awd               6
gti                        5
c1500 suburban 2wd         5
corolla                    5
corvette                   5
malibu                     5
grand prix                 5
k1500 tahoe 4wd            4
pathfinder 4wd             4
mountaineer 4wd            4
range rover                4
maxima                     3
navigator 2wd              3
a6 quattro                 3
expedition 2wd             3
land cruiser wagon 4wd     2
Name: model, dtype: int64
displ count    234.000000
mean       3.471795
std        1.291959
min        1.600000
25%        2.400000
50%        3.300000
75%        4.600000
max        7.000000
Name: displ, dtype: float64
year count     234.000000
mean     2003.500000
std         4.509646
min      1999.000000
25%      1999.000000
50%      2003.500000
75%      2008.000000
max      2008.000000
Name: year, dtype: float64
cyl count    234.000000
mean       5.888889
std        1.611534
min        4.000000
25%        4.000000
50%        6.000000
75%        8.000000
max        8.000000
Name: cyl, dtype: float64
trans auto(l4)      83
manual(m5)    58
auto(l5)      39
manual(m6)    19
auto(s6)      16
auto(l6)       6
auto(av)       5
auto(s5)       3
auto(s4)       3
auto(l3)       2
Name: trans, dtype: int64
drv f    106
4    103
r     25
Name: drv, dtype: int64
cty count    234.000000
mean      16.858974
std        4.255946
min        9.000000
25%       14.000000
50%       17.000000
75%       19.000000
max       35.000000
Name: cty, dtype: float64
hwy count    234.000000
mean      23.440171
std        5.954643
min       12.000000
25%       18.000000
50%       24.000000
75%       27.000000
max       44.000000
Name: hwy, dtype: float64
fl r    168
p     52
e      8
d      5
c      1
Name: fl, dtype: int64
category suv           62
compact       47
midsize       41
subcompact    35
pickup        33
minivan       11
2seater        5
Name: category, dtype: int64

- 시리즈 형태로 반복문을 이용해서 조건문을 더욱 정교하게 만들어보자!

- mpg 데이터 중에서 trans 변수에 m5 값이 있는 데이터를 출력하여 제조사별 카운팅을 하고 싶다!

- m5만 추출하는 함수를 만들어 보자!

In [62]:
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [63]:
def get_trans_spe(series):
    tr_cnt =len([ _ for x in series if x[0] in 'm6'])
    return tr_cnt

- 제조사별로 카운팅을 해야한다!

In [65]:
get_trans_spe(mpg.trans)

77

In [64]:
mpg.groupby('manufacturer').agg({'trans':get_trans_spe}).reset_index()

   manufacturer  trans
0          audi      7
1     chevrolet      3
2         dodge      7
3          ford      8
4         honda      5
5       hyundai      7
6          jeep      0
7    land rover      0
8       lincoln      0
9       mercury      0
10       nissan      5
11      pontiac      0
12       subaru      7
13       toyota     14
14   volkswagen     14

- 연도별로 cty 평균이 16미만 친구들과 16이상이 친구들을 묶어보자!

In [68]:
def get_y_cty(series):
    if mpg.iloc[series.index[0], : ]['year']==2008:
        cty_cnt = len([_ for x in series if x>=16])
    else:
        cty_cnt = len([_ for x in series if x<16])
    return cty_cnt

In [76]:
mpg.groupby('year').agg({'cty':get_y_cty}).reset_index()

   year  cty
0  1999   48
1  2008   68


### 데이터를 나눌 수 있다.
- cut 함수를 사용하여 원하는 값의 구간별로 레이블을 넣어서 전처리 할 수 있다.

In [77]:
pd.cut(mpg['cty'], bins = [0,10,15,20], labels= ['bad','good','very good']).describe()

count      189
unique       3
top       good
freq        92
Name: cty, dtype: object

## 필수과제 
- 반복문을 동일한 mpg 값이 아닌 변경하여 배운 반복문 코드를 응용하여 최소 5개 이상 코드 작성