### 복습과제

## 반복문을 통한 데이터 프레임 접근

In [2]:
a = ['A','B','C','D']

In [3]:
for i in a:
    print(i)

A
B
C
D

In [4]:
for i in range(len(a)):
    print(a[i])

A
B
C
D

## 데이터프레임 접근

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame({'과목':['국어','수학','영어','과학'],
                  '성적':[50,100,80,70]})

In [7]:
df

   과목   성적
0  국어   50
1  수학  100
2  영어   80
3  과학   70

In [8]:
df.columns #컬럼

Index(['과목', '성적'], dtype='object')

In [9]:
df.index #인덱스

RangeIndex(start=0, stop=4, step=1)

In [10]:
df['과목']

0    국어
1    수학
2    영어
3    과학
Name: 과목, dtype: object

In [11]:
df.iloc[2]

과목    영어
성적    80
Name: 2, dtype: object

## 반복문으로 데이터프레임 접근

In [12]:
for i in df:
    print(i)

과목
성적

In [13]:
df['과목']

0    국어
1    수학
2    영어
3    과학
Name: 과목, dtype: object

In [14]:
for i in df['과목']:
    print(i)

국어
수학
영어
과학

In [15]:
for i in range(len(df['과목'])):
    print(df.과목[i])

국어
수학
영어
과학

In [16]:
for i in range(len(df)):
    print(df.과목.loc[i])

국어
수학
영어
과학

In [17]:
for i in range(len(df)):
    print(df.과목.iloc[i])

국어
수학
영어
과학

In [18]:
mpg = pd.read_csv('mpg.csv')

In [19]:
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [20]:
for i in mpg.manufacturer:
    print(i)

audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
audi
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
chevrolet
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
dodge
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
ford
honda
honda
honda
honda
honda
honda
honda
honda
honda
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
hyundai
jeep
jeep
jeep
jeep
jeep
jeep
jeep
jeep
land rover
land rover
land rover
land rover
lincoln
lincoln
lincoln
mercury
mercury
mercury
mercury
nissan
nissan
nissan
nissan
nissan
nissan
nissan
nissan
nissan
nissan
nissan
nissan
nissan
pontiac
pontiac
pontiac
pontiac
pontiac
subaru
subaru
subaru
subaru
subaru
subaru
subaru
subaru
subaru
subaru
subaru
subaru
subaru
subaru
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
toyota
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen
volkswagen

In [21]:
#두 개 이상의 컬럼 가져오기
for i, j, k in zip(mpg.manufacturer, mpg.displ, mpg.year):
    print(i, j, k)

audi 1.8 1999
audi 1.8 1999
audi 2.0 2008
audi 2.0 2008
audi 2.8 1999
audi 2.8 1999
audi 3.1 2008
audi 1.8 1999
audi 1.8 1999
audi 2.0 2008
audi 2.0 2008
audi 2.8 1999
audi 2.8 1999
audi 3.1 2008
audi 3.1 2008
audi 2.8 1999
audi 3.1 2008
audi 4.2 2008
chevrolet 5.3 2008
chevrolet 5.3 2008
chevrolet 5.3 2008
chevrolet 5.7 1999
chevrolet 6.0 2008
chevrolet 5.7 1999
chevrolet 5.7 1999
chevrolet 6.2 2008
chevrolet 6.2 2008
chevrolet 7.0 2008
chevrolet 5.3 2008
chevrolet 5.3 2008
chevrolet 5.7 1999
chevrolet 6.5 1999
chevrolet 2.4 1999
chevrolet 2.4 2008
chevrolet 3.1 1999
chevrolet 3.5 2008
chevrolet 3.6 2008
dodge 2.4 1999
dodge 3.0 1999
dodge 3.3 1999
dodge 3.3 1999
dodge 3.3 2008
dodge 3.3 2008
dodge 3.3 2008
dodge 3.8 1999
dodge 3.8 1999
dodge 3.8 2008
dodge 4.0 2008
dodge 3.7 2008
dodge 3.7 2008
dodge 3.9 1999
dodge 3.9 1999
dodge 4.7 2008
dodge 4.7 2008
dodge 4.7 2008
dodge 5.2 1999
dodge 5.2 1999
dodge 3.9 1999
dodge 4.7 2008
dodge 4.7 2008
dodge 4.7 2008
dodge 5.2 1999
dodge 5.7 2008
dodge 5.9 1999
dodge 4.7 2008
dodge 4.7 2008
dodge 4.7 2008
dodge 4.7 2008
dodge 4.7 2008
dodge 4.7 2008
dodge 5.2 1999
dodge 5.2 1999
dodge 5.7 2008
dodge 5.9 1999
ford 4.6 1999
ford 5.4 1999
ford 5.4 2008
ford 4.0 1999
ford 4.0 1999
ford 4.0 1999
ford 4.0 2008
ford 4.6 2008
ford 5.0 1999
ford 4.2 1999
ford 4.2 1999
ford 4.6 1999
ford 4.6 1999
ford 4.6 2008
ford 5.4 1999
ford 5.4 2008
ford 3.8 1999
ford 3.8 1999
ford 4.0 2008
ford 4.0 2008
ford 4.6 1999
ford 4.6 1999
ford 4.6 2008
ford 4.6 2008
ford 5.4 2008
honda 1.6 1999
honda 1.6 1999
honda 1.6 1999
honda 1.6 1999
honda 1.6 1999
honda 1.8 2008
honda 1.8 2008
honda 1.8 2008
honda 2.0 2008
hyundai 2.4 1999
hyundai 2.4 1999
hyundai 2.4 2008
hyundai 2.4 2008
hyundai 2.5 1999
hyundai 2.5 1999
hyundai 3.3 2008
hyundai 2.0 1999
hyundai 2.0 1999
hyundai 2.0 2008
hyundai 2.0 2008
hyundai 2.7 2008
hyundai 2.7 2008
hyundai 2.7 2008
jeep 3.0 2008
jeep 3.7 2008
jeep 4.0 1999
jeep 4.7 1999
jeep 4.7 2008
jeep 4.7 2008
jeep 5.7 2008
jeep 6.1 2008
land rover 4.0 1999
land rover 4.2 2008
land rover 4.4 2008
land rover 4.6 1999
lincoln 5.4 1999
lincoln 5.4 1999
lincoln 5.4 2008
mercury 4.0 1999
mercury 4.0 2008
mercury 4.6 2008
mercury 5.0 1999
nissan 2.4 1999
nissan 2.4 1999
nissan 2.5 2008
nissan 2.5 2008
nissan 3.5 2008
nissan 3.5 2008
nissan 3.0 1999
nissan 3.0 1999
nissan 3.5 2008
nissan 3.3 1999
nissan 3.3 1999
nissan 4.0 2008
nissan 5.6 2008
pontiac 3.1 1999
pontiac 3.8 1999
pontiac 3.8 1999
pontiac 3.8 2008
pontiac 5.3 2008
subaru 2.5 1999
subaru 2.5 1999
subaru 2.5 2008
subaru 2.5 2008
subaru 2.5 2008
subaru 2.5 2008
subaru 2.2 1999
subaru 2.2 1999
subaru 2.5 1999
subaru 2.5 1999
subaru 2.5 2008
subaru 2.5 2008
subaru 2.5 2008
subaru 2.5 2008
toyota 2.7 1999
toyota 2.7 1999
toyota 3.4 1999
toyota 3.4 1999
toyota 4.0 2008
toyota 4.7 2008
toyota 2.2 1999
toyota 2.2 1999
toyota 2.4 2008
toyota 2.4 2008
toyota 3.0 1999
toyota 3.0 1999
toyota 3.5 2008
toyota 2.2 1999
toyota 2.2 1999
toyota 2.4 2008
toyota 2.4 2008
toyota 3.0 1999
toyota 3.0 1999
toyota 3.3 2008
toyota 1.8 1999
toyota 1.8 1999
toyota 1.8 1999
toyota 1.8 2008
toyota 1.8 2008
toyota 4.7 1999
toyota 5.7 2008
toyota 2.7 1999
toyota 2.7 1999
toyota 2.7 2008
toyota 3.4 1999
toyota 3.4 1999
toyota 4.0 2008
toyota 4.0 2008
volkswagen 2.0 1999
volkswagen 2.0 1999
volkswagen 2.0 2008
volkswagen 2.0 2008
volkswagen 2.8 1999
volkswagen 1.9 1999
volkswagen 2.0 1999
volkswagen 2.0 1999
volkswagen 2.0 2008
volkswagen 2.0 2008
volkswagen 2.5 2008
volkswagen 2.5 2008
volkswagen 2.8 1999
volkswagen 2.8 1999
volkswagen 1.9 1999
volkswagen 1.9 1999
volkswagen 2.0 1999
volkswagen 2.0 1999
volkswagen 2.5 2008
volkswagen 2.5 2008
volkswagen 1.8 1999
volkswagen 1.8 1999
volkswagen 2.0 2008
volkswagen 2.0 2008
volkswagen 2.8 1999
volkswagen 2.8 1999
volkswagen 3.6 2008

In [22]:
#해당 값을 리스트 안에 넣기
a=[]
b=[]
c=[]

for i, j, k in zip(mpg.manufacturer, mpg.displ, mpg.year):
    a.append(i)
    b.append(j)
    c.append(k)

print(a)

['audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'audi', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'chevrolet', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'ford', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'hyundai', 'jeep', 'jeep', 'jeep', 'jeep', 'jeep', 'jeep', 'jeep', 'jeep', 'land rover', 'land rover', 'land rover', 'land rover', 'lincoln', 'lincoln', 'lincoln', 'mercury', 'mercury', 'mercury', 'mercury', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'pontiac', 'pontiac', 'pontiac', 'pontiac', 'pontiac', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen']

In [23]:
#mpg데이터 중 model, hwy가 평균 이상인 데이터만 반복문으로 가져오기
mpg.hwy.mean()

23.44017094017094

In [24]:
for i, j in zip(mpg.model, mpg.hwy): #수치형데이터를 if문으로 만들기
    if j >= 16.8:
        print(i, j)

a4 29
a4 29
a4 31
a4 30
a4 26
a4 26
a4 27
a4 quattro 26
a4 quattro 25
a4 quattro 28
a4 quattro 27
a4 quattro 25
a4 quattro 25
a4 quattro 25
a4 quattro 25
a6 quattro 24
a6 quattro 25
a6 quattro 23
c1500 suburban 2wd 20
c1500 suburban 2wd 20
c1500 suburban 2wd 17
c1500 suburban 2wd 17
corvette 26
corvette 23
corvette 26
corvette 25
corvette 24
k1500 tahoe 4wd 19
k1500 tahoe 4wd 17
malibu 27
malibu 30
malibu 26
malibu 29
malibu 26
caravan 2wd 24
caravan 2wd 24
caravan 2wd 22
caravan 2wd 22
caravan 2wd 24
caravan 2wd 24
caravan 2wd 17
caravan 2wd 22
caravan 2wd 21
caravan 2wd 23
caravan 2wd 23
dakota pickup 4wd 19
dakota pickup 4wd 18
dakota pickup 4wd 17
dakota pickup 4wd 17
dakota pickup 4wd 19
dakota pickup 4wd 19
dakota pickup 4wd 17
durango 4wd 17
durango 4wd 17
durango 4wd 17
durango 4wd 18
ram 1500 pickup 4wd 17
ram 1500 pickup 4wd 17
ram 1500 pickup 4wd 17
expedition 2wd 17
expedition 2wd 17
expedition 2wd 18
explorer 4wd 17
explorer 4wd 19
explorer 4wd 17
explorer 4wd 19
explorer 4wd 19
explorer 4wd 17
f150 pickup 4wd 17
f150 pickup 4wd 17
f150 pickup 4wd 17
f150 pickup 4wd 17
mustang 26
mustang 25
mustang 26
mustang 24
mustang 21
mustang 22
mustang 23
mustang 22
mustang 20
civic 33
civic 32
civic 32
civic 29
civic 32
civic 34
civic 36
civic 36
civic 29
sonata 26
sonata 27
sonata 30
sonata 31
sonata 26
sonata 26
sonata 28
tiburon 26
tiburon 29
tiburon 28
tiburon 27
tiburon 24
tiburon 24
tiburon 24
grand cherokee 4wd 22
grand cherokee 4wd 19
grand cherokee 4wd 20
grand cherokee 4wd 17
grand cherokee 4wd 19
grand cherokee 4wd 18
range rover 18
range rover 18
navigator 2wd 17
navigator 2wd 18
mountaineer 4wd 17
mountaineer 4wd 19
mountaineer 4wd 19
mountaineer 4wd 17
altima 29
altima 27
altima 31
altima 32
altima 27
altima 26
maxima 26
maxima 25
maxima 25
pathfinder 4wd 17
pathfinder 4wd 17
pathfinder 4wd 20
pathfinder 4wd 18
grand prix 26
grand prix 26
grand prix 27
grand prix 28
grand prix 25
forester awd 25
forester awd 24
forester awd 27
forester awd 25
forester awd 26
forester awd 23
impreza awd 26
impreza awd 26
impreza awd 26
impreza awd 26
impreza awd 25
impreza awd 27
impreza awd 25
impreza awd 27
4runner 4wd 20
4runner 4wd 20
4runner 4wd 19
4runner 4wd 17
4runner 4wd 20
4runner 4wd 17
camry 29
camry 27
camry 31
camry 31
camry 26
camry 26
camry 28
camry solara 27
camry solara 29
camry solara 31
camry solara 31
camry solara 26
camry solara 26
camry solara 27
corolla 30
corolla 33
corolla 35
corolla 37
corolla 35
land cruiser wagon 4wd 18
toyota tacoma 4wd 20
toyota tacoma 4wd 20
toyota tacoma 4wd 22
toyota tacoma 4wd 17
toyota tacoma 4wd 19
toyota tacoma 4wd 18
toyota tacoma 4wd 20
gti 29
gti 26
gti 29
gti 29
gti 24
jetta 44
jetta 29
jetta 26
jetta 29
jetta 29
jetta 29
jetta 29
jetta 23
jetta 24
new beetle 44
new beetle 41
new beetle 29
new beetle 26
new beetle 28
new beetle 29
passat 29
passat 29
passat 28
passat 29
passat 26
passat 26
passat 26

In [25]:
car_wt= ['a4','passat']
car_cty = [18]
for i, j in zip(mpg.model, mpg.cty):
    if i in car_wt and j in car_cty:
        print(i,j)

a4 18
a4 18
a4 18
passat 18
passat 18

## 반복문 함수

* iterrows

In [26]:
#idx:인덱스, row:전체 데이터프레임
for idx, row in mpg.iterrows():
    print(idx,row)

0 manufacturer        audi
model                 a4
displ                1.8
year                1999
cyl                    4
trans           auto(l5)
drv                    f
cty                   18
hwy                   29
fl                     p
category         compact
Name: 0, dtype: object
1 manufacturer          audi
model                   a4
displ                  1.8
year                  1999
cyl                      4
trans           manual(m5)
drv                      f
cty                     21
hwy                     29
fl                       p
category           compact
Name: 1, dtype: object
2 manufacturer          audi
model                   a4
displ                  2.0
year                  2008
cyl                      4
trans           manual(m6)
drv                      f
cty                     20
hwy                     31
fl                       p
category           compact
Name: 2, dtype: object
3 manufacturer        audi
model                 a4
displ                2.0
year                2008
cyl                    4
trans           auto(av)
drv                    f
cty                   21
hwy                   30
fl                     p
category         compact
Name: 3, dtype: object
4 manufacturer        audi
model                 a4
displ                2.8
year                1999
cyl                    6
trans           auto(l5)
drv                    f
cty                   16
hwy                   26
fl                     p
category         compact
Name: 4, dtype: object
5 manufacturer          audi
model                   a4
displ                  2.8
year                  1999
cyl                      6
trans           manual(m5)
drv                      f
cty                     18
hwy                     26
fl                       p
category           compact
Name: 5, dtype: object
6 manufacturer        audi
model                 a4
displ                3.1
year                2008
cyl                    6
trans           auto(av)
drv                    f
cty                   18
hwy                   27
fl                     p
category         compact
Name: 6, dtype: object
7 manufacturer          audi
model           a4 quattro
displ                  1.8
year                  1999
cyl                      4
trans           manual(m5)
drv                      4
cty                     18
hwy                     26
fl                       p
category           compact
Name: 7, dtype: object
8 manufacturer          audi
model           a4 quattro
displ                  1.8
year                  1999
cyl                      4
trans             auto(l5)
drv                      4
cty                     16
hwy                     25
fl                       p
category           compact
Name: 8, dtype: object
9 manufacturer          audi
model           a4 quattro
displ                  2.0
year                  2008
cyl                      4
trans           manual(m6)
drv                      4
cty                     20
hwy                     28
fl                       p
category           compact
Name: 9, dtype: object
10 manufacturer          audi
model           a4 quattro
displ                  2.0
year                  2008
cyl                      4
trans             auto(s6)
drv                      4
cty                     19
hwy                     27
fl                       p
category           compact
Name: 10, dtype: object
11 manufacturer          audi
model           a4 quattro
displ                  2.8
year                  1999
cyl                      6
trans             auto(l5)
drv                      4
cty                     15
hwy                     25
fl                       p
category           compact
Name: 11, dtype: object
12 manufacturer          audi
model           a4 quattro
displ                  2.8
year                  1999
cyl                      6
trans           manual(m5)
drv                      4
cty                     17
hwy                     25
fl                       p
category           compact
Name: 12, dtype: object
13 manufacturer          audi
model           a4 quattro
displ                  3.1
year                  2008
cyl                      6
trans             auto(s6)
drv                      4
cty                     17
hwy                     25
fl                       p
category           compact
Name: 13, dtype: object
14 manufacturer          audi
model           a4 quattro
displ                  3.1
year                  2008
cyl                      6
trans           manual(m6)
drv                      4
cty                     15
hwy                     25
fl                       p
category           compact
Name: 14, dtype: object
15 manufacturer          audi
model           a6 quattro
displ                  2.8
year                  1999
cyl                      6
trans             auto(l5)
drv                      4
cty                     15
hwy                     24
fl                       p
category           midsize
Name: 15, dtype: object
16 manufacturer          audi
model           a6 quattro
displ                  3.1
year                  2008
cyl                      6
trans             auto(s6)
drv                      4
cty                     17
hwy                     25
fl                       p
category           midsize
Name: 16, dtype: object
17 manufacturer          audi
model           a6 quattro
displ                  4.2
year                  2008
cyl                      8
trans             auto(s6)
drv                      4
cty                     16
hwy                     23
fl                       p
category           midsize
Name: 17, dtype: object
18 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             14
hwy                             20
fl                               r
category                       suv
Name: 18, dtype: object
19 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             11
hwy                             15
fl                               e
category                       suv
Name: 19, dtype: object
20 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.3
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             14
hwy                             20
fl                               r
category                       suv
Name: 20, dtype: object
21 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          5.7
year                          1999
cyl                              8
trans                     auto(l4)
drv                              r
cty                             13
hwy                             17
fl                               r
category                       suv
Name: 21, dtype: object
22 manufacturer             chevrolet
model           c1500 suburban 2wd
displ                          6.0
year                          2008
cyl                              8
trans                     auto(l4)
drv                              r
cty                             12
hwy                             17
fl                               r
category                       suv
Name: 22, dtype: object
23 manufacturer     chevrolet
model             corvette
displ                  5.7
year                  1999
cyl                      8
trans           manual(m6)
drv                      r
cty                     16
hwy                     26
fl                       p
category           2seater
Name: 23, dtype: object
24 manufacturer    chevrolet
model            corvette
displ                 5.7
year                 1999
cyl                     8
trans            auto(l4)
drv                     r
cty                    15
hwy                    23
fl                      p
category          2seater
Name: 24, dtype: object
25 manufacturer     chevrolet
model             corvette
displ                  6.2
year                  2008
cyl                      8
trans           manual(m6)
drv                      r
cty                     16
hwy                     26
fl                       p
category           2seater
Name: 25, dtype: object
26 manufacturer    chevrolet
model            corvette
displ                 6.2
year                 2008
cyl                     8
trans            auto(s6)
drv                     r
cty                    15
hwy                    25
fl                      p
category          2seater
Name: 26, dtype: object
27 manufacturer     chevrolet
model             corvette
displ                  7.0
year                  2008
cyl                      8
trans           manual(m6)
drv                      r
cty                     15
hwy                     24
fl                       p
category           2seater
Name: 27, dtype: object
28 manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.3
year                       2008
cyl                           8
trans                  auto(l4)
drv                           4
cty                          14
hwy                          19
fl                            r
category                    suv
Name: 28, dtype: object
29 manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.3
year                       2008
cyl                           8
trans                  auto(l4)
drv                           4
cty                          11
hwy                          14
fl                            e
category                    suv
Name: 29, dtype: object
30 manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       5.7
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          11
hwy                          15
fl                            r
category                    suv
Name: 30, dtype: object
31 manufacturer          chevrolet
model           k1500 tahoe 4wd
displ                       6.5
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          14
hwy                          17
fl                            d
category                    suv
Name: 31, dtype: object
32 manufacturer    chevrolet
model              malibu
displ                 2.4
year                 1999
cyl                     4
trans            auto(l4)
drv                     f
cty                    19
hwy                    27
fl                      r
category          midsize
Name: 32, dtype: object
33 manufacturer    chevrolet
model              malibu
displ                 2.4
year                 2008
cyl                     4
trans            auto(l4)
drv                     f
cty                    22
hwy                    30
fl                      r
category          midsize
Name: 33, dtype: object
34 manufacturer    chevrolet
model              malibu
displ                 3.1
year                 1999
cyl                     6
trans            auto(l4)
drv                     f
cty                    18
hwy                    26
fl                      r
category          midsize
Name: 34, dtype: object
35 manufacturer    chevrolet
model              malibu
displ                 3.5
year                 2008
cyl                     6
trans            auto(l4)
drv                     f
cty                    18
hwy                    29
fl                      r
category          midsize
Name: 35, dtype: object
36 manufacturer    chevrolet
model              malibu
displ                 3.6
year                 2008
cyl                     6
trans            auto(s6)
drv                     f
cty                    17
hwy                    26
fl                      r
category          midsize
Name: 36, dtype: object
37 manufacturer          dodge
model           caravan 2wd
displ                   2.4
year                   1999
cyl                       4
trans              auto(l3)
drv                       f
cty                      18
hwy                      24
fl                        r
category            minivan
Name: 37, dtype: object
38 manufacturer          dodge
model           caravan 2wd
displ                   3.0
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 38, dtype: object
39 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      16
hwy                      22
fl                        r
category            minivan
Name: 39, dtype: object
40 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      16
hwy                      22
fl                        r
category            minivan
Name: 40, dtype: object
41 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 41, dtype: object
42 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      17
hwy                      24
fl                        r
category            minivan
Name: 42, dtype: object
43 manufacturer          dodge
model           caravan 2wd
displ                   3.3
year                   2008
cyl                       6
trans              auto(l4)
drv                       f
cty                      11
hwy                      17
fl                        e
category            minivan
Name: 43, dtype: object
44 manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      15
hwy                      22
fl                        r
category            minivan
Name: 44, dtype: object
45 manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   1999
cyl                       6
trans              auto(l4)
drv                       f
cty                      15
hwy                      21
fl                        r
category            minivan
Name: 45, dtype: object
46 manufacturer          dodge
model           caravan 2wd
displ                   3.8
year                   2008
cyl                       6
trans              auto(l6)
drv                       f
cty                      16
hwy                      23
fl                        r
category            minivan
Name: 46, dtype: object
47 manufacturer          dodge
model           caravan 2wd
displ                   4.0
year                   2008
cyl                       6
trans              auto(l6)
drv                       f
cty                      16
hwy                      23
fl                        r
category            minivan
Name: 47, dtype: object
48 manufacturer                dodge
model           dakota pickup 4wd
displ                         3.7
year                         2008
cyl                             6
trans                  manual(m6)
drv                             4
cty                            15
hwy                            19
fl                              r
category                   pickup
Name: 48, dtype: object
49 manufacturer                dodge
model           dakota pickup 4wd
displ                         3.7
year                         2008
cyl                             6
trans                    auto(l4)
drv                             4
cty                            14
hwy                            18
fl                              r
category                   pickup
Name: 49, dtype: object
50 manufacturer                dodge
model           dakota pickup 4wd
displ                         3.9
year                         1999
cyl                             6
trans                    auto(l4)
drv                             4
cty                            13
hwy                            17
fl                              r
category                   pickup
Name: 50, dtype: object
51 manufacturer                dodge
model           dakota pickup 4wd
displ                         3.9
year                         1999
cyl                             6
trans                  manual(m5)
drv                             4
cty                            14
hwy                            17
fl                              r
category                   pickup
Name: 51, dtype: object
52 manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                            14
hwy                            19
fl                              r
category                   pickup
Name: 52, dtype: object
53 manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                            14
hwy                            19
fl                              r
category                   pickup
Name: 53, dtype: object
54 manufacturer                dodge
model           dakota pickup 4wd
displ                         4.7
year                         2008
cyl                             8
trans                    auto(l5)
drv                             4
cty                             9
hwy                            12
fl                              e
category                   pickup
Name: 54, dtype: object
55 manufacturer                dodge
model           dakota pickup 4wd
displ                         5.2
year                         1999
cyl                             8
trans                  manual(m5)
drv                             4
cty                            11
hwy                            17
fl                              r
category                   pickup
Name: 55, dtype: object
56 manufacturer                dodge
model           dakota pickup 4wd
displ                         5.2
year                         1999
cyl                             8
trans                    auto(l4)
drv                             4
cty                            11
hwy                            15
fl                              r
category                   pickup
Name: 56, dtype: object
57 manufacturer          dodge
model           durango 4wd
displ                   3.9
year                   1999
cyl                       6
trans              auto(l4)
drv                       4
cty                      13

126 manufacturer                  jeep
model           grand cherokee 4wd
displ                          4.7
year                          2008
cyl                              8
trans                     auto(l5)
drv                              4
cty                              9
hwy                             12
fl                               e
category                       suv
Name: 126, dtype: object
127 manufacturer                  jeep
model           grand cherokee 4wd
displ                          4.7
year                          2008
cyl                              8
trans                     auto(l5)
drv                              4
cty                             14
hwy                             19
fl                               r
category                       suv
Name: 127, dtype: object
128 manufacturer                  jeep
model           grand cherokee 4wd
displ                          5.7
year                          2008
cyl                              8
trans                     auto(l5)
drv                              4
cty                             13
hwy                             18
fl                               r
category                       suv
Name: 128, dtype: object
129 manufacturer                  jeep
model           grand cherokee 4wd
displ                          6.1
year                          2008
cyl                              8
trans                     auto(l5)
drv                              4
cty                             11
hwy                             14
fl                               p
category                       suv
Name: 129, dtype: object
130 manufacturer     land rover
model           range rover
displ                   4.0
year                   1999
cyl                       8
trans              auto(l4)
drv                       4
cty                      11
hwy                      15
fl                        p
category                suv
Name: 130, dtype: object
131 manufacturer     land rover
model           range rover
displ                   4.2
year                   2008
cyl                       8
trans              auto(s6)
drv                       4
cty                      12
hwy                      18
fl                        r
category                suv
Name: 131, dtype: object
132 manufacturer     land rover
model           range rover
displ                   4.4
year                   2008
cyl                       8
trans              auto(s6)
drv                       4
cty                      12
hwy                      18
fl                        r
category                suv
Name: 132, dtype: object
133 manufacturer     land rover
model           range rover
displ                   4.6
year                   1999
cyl                       8
trans              auto(l4)
drv                       4
cty                      11
hwy                      15
fl                        p
category                suv
Name: 133, dtype: object
134 manufacturer          lincoln
model           navigator 2wd
displ                     5.4
year                     1999
cyl                         8
trans                auto(l4)
drv                         r
cty                        11
hwy                        17
fl                          r
category                  suv
Name: 134, dtype: object
135 manufacturer          lincoln
model           navigator 2wd
displ                     5.4
year                     1999
cyl                         8
trans                auto(l4)
drv                         r
cty                        11
hwy                        16
fl                          p
category                  suv
Name: 135, dtype: object
136 manufacturer          lincoln
model           navigator 2wd
displ                     5.4
year                     2008
cyl                         8
trans                auto(l6)
drv                         r
cty                        12
hwy                        18
fl                          r
category                  suv
Name: 136, dtype: object
137 manufacturer            mercury
model           mountaineer 4wd
displ                       4.0
year                       1999
cyl                           6
trans                  auto(l5)
drv                           4
cty                          14
hwy                          17
fl                            r
category                    suv
Name: 137, dtype: object
138 manufacturer            mercury
model           mountaineer 4wd
displ                       4.0
year                       2008
cyl                           6
trans                  auto(l5)
drv                           4
cty                          13
hwy                          19
fl                            r
category                    suv
Name: 138, dtype: object
139 manufacturer            mercury
model           mountaineer 4wd
displ                       4.6
year                       2008
cyl                           8
trans                  auto(l6)
drv                           4
cty                          13
hwy                          19
fl                            r
category                    suv
Name: 139, dtype: object
140 manufacturer            mercury
model           mountaineer 4wd
displ                       5.0
year                       1999
cyl                           8
trans                  auto(l4)
drv                           4
cty                          13
hwy                          17
fl                            r
category                    suv
Name: 140, dtype: object
141 manufacturer        nissan
model               altima
displ                  2.4
year                  1999
cyl                      4
trans           manual(m5)
drv                      f
cty                     21
hwy                     29
fl                       r
category           compact
Name: 141, dtype: object
142 manufacturer      nissan
model             altima
displ                2.4
year                1999
cyl                    4
trans           auto(l4)
drv                    f
cty                   19
hwy                   27
fl                     r
category         compact
Name: 142, dtype: object
143 manufacturer      nissan
model             altima
displ                2.5
year                2008
cyl                    4
trans           auto(av)
drv                    f
cty                   23
hwy                   31
fl                     r
category         midsize
Name: 143, dtype: object
144 manufacturer        nissan
model               altima
displ                  2.5
year                  2008
cyl                      4
trans           manual(m6)
drv                      f
cty                     23
hwy                     32
fl                       r
category           midsize
Name: 144, dtype: object
145 manufacturer        nissan
model               altima
displ                  3.5
year                  2008
cyl                      6
trans           manual(m6)
drv                      f
cty                     19
hwy                     27
fl                       p
category           midsize
Name: 145, dtype: object
146 manufacturer      nissan
model             altima
displ                3.5
year                2008
cyl                    6
trans           auto(av)
drv                    f
cty                   19
hwy                   26
fl                     p
category         midsize
Name: 146, dtype: object
147 manufacturer      nissan
model             maxima
displ                3.0
year                1999
cyl                    6
trans           auto(l4)
drv                    f
cty                   18
hwy                   26
fl                     r
category         midsize
Name: 147, dtype: object
148 manufacturer        nissan
model               maxima
displ                  3.0
year                  1999
cyl                      6
trans           manual(m5)
drv                      f
cty                     19
hwy                     25
fl                       r
category           midsize
Name: 148, dtype: object
149 manufacturer      nissan
model             maxima
displ                3.5
year                2008
cyl                    6
trans           auto(av)
drv                    f
cty                   19
hwy                   25
fl                     p
category         midsize
Name: 149, dtype: object
150 manufacturer            nissan
model           pathfinder 4wd
displ                      3.3
year                      1999
cyl                          6
trans                 auto(l4)
drv                          4
cty                         14
hwy                         17
fl                           r
category                   suv
Name: 150, dtype: object
151 manufacturer            nissan
model           pathfinder 4wd
displ                      3.3
year                      1999
cyl                          6
trans               manual(m5)
drv                          4
cty                         15
hwy                         17
fl                           r
category                   suv
Name: 151, dtype: object
152 manufacturer            nissan
model           pathfinder 4wd
displ                      4.0
year                      2008
cyl                          6
trans                 auto(l5)
drv                          4
cty                         14
hwy                         20
fl                           p
category                   suv
Name: 152, dtype: object
153 manufacturer            nissan
model           pathfinder 4wd
displ                      5.6
year                      2008
cyl                          8
trans                 auto(s5)
drv                          4
cty                         12
hwy                         18
fl                           p
category                   suv
Name: 153, dtype: object
154 manufacturer       pontiac
model           grand prix
displ                  3.1
year                  1999
cyl                      6
trans             auto(l4)
drv                      f
cty                     18
hwy                     26
fl                       r
category           midsize
Name: 154, dtype: object
155 manufacturer       pontiac
model           grand prix
displ                  3.8
year                  1999
cyl                      6
trans             auto(l4)
drv                      f
cty                     16
hwy                     26
fl                       p
category           midsize
Name: 155, dtype: object
156 manufacturer       pontiac
model           grand prix
displ                  3.8
year                  1999
cyl                      6
trans             auto(l4)
drv                      f
cty                     17
hwy                     27
fl                       r
category           midsize
Name: 156, dtype: object
157 manufacturer       pontiac
model           grand prix
displ                  3.8
year                  2008
cyl                      6
trans             auto(l4)
drv                      f
cty                     18
hwy                     28
fl                       r
category           midsize
Name: 157, dtype: object
158 manufacturer       pontiac
model           grand prix
displ                  5.3
year                  2008
cyl                      8
trans             auto(s4)
drv                      f
cty                     16
hwy                     25
fl                       p
category           midsize
Name: 158, dtype: object
159 manufacturer          subaru
model           forester awd
displ                    2.5
year                    1999
cyl                        4
trans             manual(m5)
drv                        4
cty                       18
hwy                       25
fl                         r
category                 suv
Name: 159, dtype: object
160 manufacturer          subaru
model           forester awd
displ                    2.5
year                    1999
cyl                        4
trans               auto(l4)
drv                        4
cty                       18
hwy                       24
fl                         r
category                 suv
Name: 160, dtype: object
161 manufacturer          subaru
model           forester awd
displ                    2.5
year                    2008
cyl                        4
trans             manual(m5)
drv                        4
cty                       20
hwy                       27
fl                         r
category                 suv
Name: 161, dtype: object
162 manufacturer          subaru
model           forester awd
displ                    2.5
year                    2008
cyl                        4
trans             manual(m5)
drv                        4
cty                       19
hwy                       25
fl                         p
category                 suv
Name: 162, dtype: object
163 manufacturer          subaru
model           forester awd
displ                    2.5
year                    2008
cyl                        4
trans               auto(l4)
drv                        4
cty                       20
hwy                       26
fl                         r
category                 suv
Name: 163, dtype: object
164 manufacturer          subaru
model           forester awd
displ                    2.5
year                    2008
cyl                        4
trans               auto(l4)
drv                        4
cty                       18
hwy                       23
fl                         p
category                 suv
Name: 164, dtype: object
165 manufacturer         subaru
model           impreza awd
displ                   2.2
year                   1999
cyl                       4
trans              auto(l4)
drv                       4
cty                      21
hwy                      26
fl                        r
category         subcompact
Name: 165, dtype: object
166 manufacturer         subaru
model           impreza awd
displ                   2.2
year                   1999
cyl                       4
trans            manual(m5)
drv                       4
cty                      19
hwy                      26
fl                        r
category         subcompact
Name: 166, dtype: object
167 manufacturer         subaru
model           impreza awd
displ                   2.5
year                   1999
cyl                       4
trans            manual(m5)
drv                       4
cty                      19
hwy                      26
fl                        r
category         subcompact
Name: 167, dtype: object
168 manufacturer         subaru
model           impreza awd
displ                   2.5
year                   1999
cyl                       4
trans              auto(l4)
drv                       4
cty                      19
hwy                      26
fl                        r
category         subcompact
Name: 168, dtype: object
169 manufacturer         subaru
model           impreza awd
displ                   2.5
year                   2008
cyl                       4
trans              auto(s4)
drv                       4
cty                      20
hwy                      25
fl                        p
category            compact
Name: 169, dtype: object
170 manufacturer         subaru
model           impreza awd
displ                   2.5
year                   2008
cyl                       4
trans              auto(s4)
drv                       4
cty                      20
hwy                      27
fl                        r
category            compact
Name: 170, dtype: object
171 manufacturer         subaru
model           impreza awd
displ                   2.5
year                   2008
cyl                       4
trans            manual(m5)
drv                       4
cty                      19
hwy                      25
fl                        p
category            compact
Name: 171, dtype: object
172 manufacturer         subaru
model           impreza awd
displ                   2.5
year                   2008
cyl                       4
trans            manual(m5)
drv                       4
cty                      20
hwy                      27
fl                        r
category            compact
Name: 172, dtype: object
173 manufacturer         toyota
model           4runner 4wd
displ                   2.7
year                   1999
cyl                       4
trans            manual(m5)
drv                       4
cty                      15
hwy                      20
fl                        r
category                suv
Name: 173, dtype: object
174 manufacturer         toyota
model           4runner 4wd
displ                   2.7
year                   1999
cyl                       4
trans              auto(l4)
drv                       4
cty                      16
hwy                      20
fl                        r
category                suv
Name: 174, dtype: object
175 manufacturer         toyota
model           4runner 4wd
displ                   3.4
year                   1999
cyl                       6
trans              auto(l4)
drv                       4
cty                      15
hwy                      19
fl                        r
category                suv
Name: 175, dtype: object
176 manufacturer         toyota
model           4runner 4wd
displ                   3.4
year                   1999
cyl                       6
trans            manual(m5)
drv                       4
cty                      15
hwy                      17
fl                        r
category                suv
Name: 176, dtype: object
177 manufacturer         toyota
model           4runner 4wd
displ                   4.0
year                   2008
cyl                       6
trans              auto(l5)
drv                       4
cty                      16
hwy                      20
fl                        r
category                suv
Name: 177, dtype: object
178 manufacturer         toyota
model           4runner 4wd
displ                   4.7
year                   2008
cyl                       8
trans              auto(l5)
drv                       4
cty                      14
hwy                      17
fl                        r
category                suv
Name: 178, dtype: object
179 manufacturer        toyota
model                camry
displ                  2.2
year                  1999
cyl                      4
trans           manual(m5)
drv                      f
cty                     21
hwy                     29
fl                       r
category           midsize
Name: 179, dtype: object
180 manufacturer      toyota
model              camry
displ                2.2
year                1999
cyl                    4
trans           auto(l4)
drv                    f
cty                   21
hwy                   27
fl                     r
category         midsize
Name: 180, dtype: object
181 manufacturer        toyota
model                camry
displ                  2.4
year                  2008
cyl                      4
trans           manual(m5)
drv                      f
cty                     21
hwy                     31
fl                       r
category           midsize
Name: 181, dtype: object
182 manufacturer      toyota
model              camry
displ                2.4
year                2008
cyl                    4
trans           auto(l5)
drv                    f
cty                   21
hwy                   31
fl                     r
category         midsize
Name: 182, dtype: object
183 manufacturer      toyota
model              camry
displ                3.0
year                1999
cyl                    6
trans           auto(l4)
drv                    f
cty                   18
hwy                   26
fl                     r
category         midsize
Name: 183, dtype: object
184 manufacturer        toyota
model                camry
displ                  3.0

In [28]:
for idx, row in mpg.iterrows():
    print(idx,row['hwy'])

0 29
1 29
2 31
3 30
4 26
5 26
6 27
7 26
8 25
9 28
10 27
11 25
12 25
13 25
14 25
15 24
16 25
17 23
18 20
19 15
20 20
21 17
22 17
23 26
24 23
25 26
26 25
27 24
28 19
29 14
30 15
31 17
32 27
33 30
34 26
35 29
36 26
37 24
38 24
39 22
40 22
41 24
42 24
43 17
44 22
45 21
46 23
47 23
48 19
49 18
50 17
51 17
52 19
53 19
54 12
55 17
56 15
57 17
58 17
59 12
60 17
61 16
62 18
63 15
64 16
65 12
66 17
67 17
68 16
69 12
70 15
71 16
72 17
73 15
74 17
75 17
76 18
77 17
78 19
79 17
80 19
81 19
82 17
83 17
84 17
85 16
86 16
87 17
88 15
89 17
90 26
91 25
92 26
93 24
94 21
95 22
96 23
97 22
98 20
99 33
100 32
101 32
102 29
103 32
104 34
105 36
106 36
107 29
108 26
109 27
110 30
111 31
112 26
113 26
114 28
115 26
116 29
117 28
118 27
119 24
120 24
121 24
122 22
123 19
124 20
125 17
126 12
127 19
128 18
129 14
130 15
131 18
132 18
133 15
134 17
135 16
136 18
137 17
138 19
139 19
140 17
141 29
142 27
143 31
144 32
145 27
146 26
147 26
148 25
149 25
150 17
151 17
152 20
153 18
154 26
155 26
156 27
157 28
158 25
159 25
160 24
161 27
162 25
163 26
164 23
165 26
166 26
167 26
168 26
169 25
170 27
171 25
172 27
173 20
174 20
175 19
176 17
177 20
178 17
179 29
180 27
181 31
182 31
183 26
184 26
185 28
186 27
187 29
188 31
189 31
190 26
191 26
192 27
193 30
194 33
195 35
196 37
197 35
198 15
199 18
200 20
201 20
202 22
203 17
204 19
205 18
206 20
207 29
208 26
209 29
210 29
211 24
212 44
213 29
214 26
215 29
216 29
217 29
218 29
219 23
220 24
221 44
222 41
223 29
224 26
225 28
226 29
227 29
228 29
229 28
230 29
231 26
232 26
233 26

In [29]:
for idx, row in mpg.iterrows():
    print(idx,row['model'])

0 a4
1 a4
2 a4
3 a4
4 a4
5 a4
6 a4
7 a4 quattro
8 a4 quattro
9 a4 quattro
10 a4 quattro
11 a4 quattro
12 a4 quattro
13 a4 quattro
14 a4 quattro
15 a6 quattro
16 a6 quattro
17 a6 quattro
18 c1500 suburban 2wd
19 c1500 suburban 2wd
20 c1500 suburban 2wd
21 c1500 suburban 2wd
22 c1500 suburban 2wd
23 corvette
24 corvette
25 corvette
26 corvette
27 corvette
28 k1500 tahoe 4wd
29 k1500 tahoe 4wd
30 k1500 tahoe 4wd
31 k1500 tahoe 4wd
32 malibu
33 malibu
34 malibu
35 malibu
36 malibu
37 caravan 2wd
38 caravan 2wd
39 caravan 2wd
40 caravan 2wd
41 caravan 2wd
42 caravan 2wd
43 caravan 2wd
44 caravan 2wd
45 caravan 2wd
46 caravan 2wd
47 caravan 2wd
48 dakota pickup 4wd
49 dakota pickup 4wd
50 dakota pickup 4wd
51 dakota pickup 4wd
52 dakota pickup 4wd
53 dakota pickup 4wd
54 dakota pickup 4wd
55 dakota pickup 4wd
56 dakota pickup 4wd
57 durango 4wd
58 durango 4wd
59 durango 4wd
60 durango 4wd
61 durango 4wd
62 durango 4wd
63 durango 4wd
64 ram 1500 pickup 4wd
65 ram 1500 pickup 4wd
66 ram 1500 pickup 4wd
67 ram 1500 pickup 4wd
68 ram 1500 pickup 4wd
69 ram 1500 pickup 4wd
70 ram 1500 pickup 4wd
71 ram 1500 pickup 4wd
72 ram 1500 pickup 4wd
73 ram 1500 pickup 4wd
74 expedition 2wd
75 expedition 2wd
76 expedition 2wd
77 explorer 4wd
78 explorer 4wd
79 explorer 4wd
80 explorer 4wd
81 explorer 4wd
82 explorer 4wd
83 f150 pickup 4wd
84 f150 pickup 4wd
85 f150 pickup 4wd
86 f150 pickup 4wd
87 f150 pickup 4wd
88 f150 pickup 4wd
89 f150 pickup 4wd
90 mustang
91 mustang
92 mustang
93 mustang
94 mustang
95 mustang
96 mustang
97 mustang
98 mustang
99 civic
100 civic
101 civic
102 civic
103 civic
104 civic
105 civic
106 civic
107 civic
108 sonata
109 sonata
110 sonata
111 sonata
112 sonata
113 sonata
114 sonata
115 tiburon
116 tiburon
117 tiburon
118 tiburon
119 tiburon
120 tiburon
121 tiburon
122 grand cherokee 4wd
123 grand cherokee 4wd
124 grand cherokee 4wd
125 grand cherokee 4wd
126 grand cherokee 4wd
127 grand cherokee 4wd
128 grand cherokee 4wd
129 grand cherokee 4wd
130 range rover
131 range rover
132 range rover
133 range rover
134 navigator 2wd
135 navigator 2wd
136 navigator 2wd
137 mountaineer 4wd
138 mountaineer 4wd
139 mountaineer 4wd
140 mountaineer 4wd
141 altima
142 altima
143 altima
144 altima
145 altima
146 altima
147 maxima
148 maxima
149 maxima
150 pathfinder 4wd
151 pathfinder 4wd
152 pathfinder 4wd
153 pathfinder 4wd
154 grand prix
155 grand prix
156 grand prix
157 grand prix
158 grand prix
159 forester awd
160 forester awd
161 forester awd
162 forester awd
163 forester awd
164 forester awd
165 impreza awd
166 impreza awd
167 impreza awd
168 impreza awd
169 impreza awd
170 impreza awd
171 impreza awd
172 impreza awd
173 4runner 4wd
174 4runner 4wd
175 4runner 4wd
176 4runner 4wd
177 4runner 4wd
178 4runner 4wd
179 camry
180 camry
181 camry
182 camry
183 camry
184 camry
185 camry
186 camry solara
187 camry solara
188 camry solara
189 camry solara
190 camry solara
191 camry solara
192 camry solara
193 corolla
194 corolla
195 corolla
196 corolla
197 corolla
198 land cruiser wagon 4wd
199 land cruiser wagon 4wd
200 toyota tacoma 4wd
201 toyota tacoma 4wd
202 toyota tacoma 4wd
203 toyota tacoma 4wd
204 toyota tacoma 4wd
205 toyota tacoma 4wd
206 toyota tacoma 4wd
207 gti
208 gti
209 gti
210 gti
211 gti
212 jetta
213 jetta
214 jetta
215 jetta
216 jetta
217 jetta
218 jetta
219 jetta
220 jetta
221 new beetle
222 new beetle
223 new beetle
224 new beetle
225 new beetle
226 new beetle
227 passat
228 passat
229 passat
230 passat
231 passat
232 passat
233 passat

* itertuples

In [30]:
#첫필드:인덱스, 나머지열
for row in mpg.itertuples():
    print(row)

Pandas(Index=0, manufacturer='audi', model='a4', displ=1.8, year=1999, cyl=4, trans='auto(l5)', drv='f', cty=18, hwy=29, fl='p', category='compact')
Pandas(Index=1, manufacturer='audi', model='a4', displ=1.8, year=1999, cyl=4, trans='manual(m5)', drv='f', cty=21, hwy=29, fl='p', category='compact')
Pandas(Index=2, manufacturer='audi', model='a4', displ=2.0, year=2008, cyl=4, trans='manual(m6)', drv='f', cty=20, hwy=31, fl='p', category='compact')
Pandas(Index=3, manufacturer='audi', model='a4', displ=2.0, year=2008, cyl=4, trans='auto(av)', drv='f', cty=21, hwy=30, fl='p', category='compact')
Pandas(Index=4, manufacturer='audi', model='a4', displ=2.8, year=1999, cyl=6, trans='auto(l5)', drv='f', cty=16, hwy=26, fl='p', category='compact')
Pandas(Index=5, manufacturer='audi', model='a4', displ=2.8, year=1999, cyl=6, trans='manual(m5)', drv='f', cty=18, hwy=26, fl='p', category='compact')
Pandas(Index=6, manufacturer='audi', model='a4', displ=3.1, year=2008, cyl=6, trans='auto(av)', drv='f', cty=18, hwy=27, fl='p', category='compact')
Pandas(Index=7, manufacturer='audi', model='a4 quattro', displ=1.8, year=1999, cyl=4, trans='manual(m5)', drv='4', cty=18, hwy=26, fl='p', category='compact')
Pandas(Index=8, manufacturer='audi', model='a4 quattro', displ=1.8, year=1999, cyl=4, trans='auto(l5)', drv='4', cty=16, hwy=25, fl='p', category='compact')
Pandas(Index=9, manufacturer='audi', model='a4 quattro', displ=2.0, year=2008, cyl=4, trans='manual(m6)', drv='4', cty=20, hwy=28, fl='p', category='compact')
Pandas(Index=10, manufacturer='audi', model='a4 quattro', displ=2.0, year=2008, cyl=4, trans='auto(s6)', drv='4', cty=19, hwy=27, fl='p', category='compact')
Pandas(Index=11, manufacturer='audi', model='a4 quattro', displ=2.8, year=1999, cyl=6, trans='auto(l5)', drv='4', cty=15, hwy=25, fl='p', category='compact')
Pandas(Index=12, manufacturer='audi', model='a4 quattro', displ=2.8, year=1999, cyl=6, trans='manual(m5)', drv='4', cty=17, hwy=25, fl='p', category='compact')
Pandas(Index=13, manufacturer='audi', model='a4 quattro', displ=3.1, year=2008, cyl=6, trans='auto(s6)', drv='4', cty=17, hwy=25, fl='p', category='compact')
Pandas(Index=14, manufacturer='audi', model='a4 quattro', displ=3.1, year=2008, cyl=6, trans='manual(m6)', drv='4', cty=15, hwy=25, fl='p', category='compact')
Pandas(Index=15, manufacturer='audi', model='a6 quattro', displ=2.8, year=1999, cyl=6, trans='auto(l5)', drv='4', cty=15, hwy=24, fl='p', category='midsize')
Pandas(Index=16, manufacturer='audi', model='a6 quattro', displ=3.1, year=2008, cyl=6, trans='auto(s6)', drv='4', cty=17, hwy=25, fl='p', category='midsize')
Pandas(Index=17, manufacturer='audi', model='a6 quattro', displ=4.2, year=2008, cyl=8, trans='auto(s6)', drv='4', cty=16, hwy=23, fl='p', category='midsize')
Pandas(Index=18, manufacturer='chevrolet', model='c1500 suburban 2wd', displ=5.3, year=2008, cyl=8, trans='auto(l4)', drv='r', cty=14, hwy=20, fl='r', category='suv')
Pandas(Index=19, manufacturer='chevrolet', model='c1500 suburban 2wd', displ=5.3, year=2008, cyl=8, trans='auto(l4)', drv='r', cty=11, hwy=15, fl='e', category='suv')
Pandas(Index=20, manufacturer='chevrolet', model='c1500 suburban 2wd', displ=5.3, year=2008, cyl=8, trans='auto(l4)', drv='r', cty=14, hwy=20, fl='r', category='suv')
Pandas(Index=21, manufacturer='chevrolet', model='c1500 suburban 2wd', displ=5.7, year=1999, cyl=8, trans='auto(l4)', drv='r', cty=13, hwy=17, fl='r', category='suv')
Pandas(Index=22, manufacturer='chevrolet', model='c1500 suburban 2wd', displ=6.0, year=2008, cyl=8, trans='auto(l4)', drv='r', cty=12, hwy=17, fl='r', category='suv')
Pandas(Index=23, manufacturer='chevrolet', model='corvette', displ=5.7, year=1999, cyl=8, trans='manual(m6)', drv='r', cty=16, hwy=26, fl='p', category='2seater')
Pandas(Index=24, manufacturer='chevrolet', model='corvette', displ=5.7, year=1999, cyl=8, trans='auto(l4)', drv='r', cty=15, hwy=23, fl='p', category='2seater')
Pandas(Index=25, manufacturer='chevrolet', model='corvette', displ=6.2, year=2008, cyl=8, trans='manual(m6)', drv='r', cty=16, hwy=26, fl='p', category='2seater')
Pandas(Index=26, manufacturer='chevrolet', model='corvette', displ=6.2, year=2008, cyl=8, trans='auto(s6)', drv='r', cty=15, hwy=25, fl='p', category='2seater')
Pandas(Index=27, manufacturer='chevrolet', model='corvette', displ=7.0, year=2008, cyl=8, trans='manual(m6)', drv='r', cty=15, hwy=24, fl='p', category='2seater')
Pandas(Index=28, manufacturer='chevrolet', model='k1500 tahoe 4wd', displ=5.3, year=2008, cyl=8, trans='auto(l4)', drv='4', cty=14, hwy=19, fl='r', category='suv')
Pandas(Index=29, manufacturer='chevrolet', model='k1500 tahoe 4wd', displ=5.3, year=2008, cyl=8, trans='auto(l4)', drv='4', cty=11, hwy=14, fl='e', category='suv')
Pandas(Index=30, manufacturer='chevrolet', model='k1500 tahoe 4wd', displ=5.7, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=11, hwy=15, fl='r', category='suv')
Pandas(Index=31, manufacturer='chevrolet', model='k1500 tahoe 4wd', displ=6.5, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=14, hwy=17, fl='d', category='suv')
Pandas(Index=32, manufacturer='chevrolet', model='malibu', displ=2.4, year=1999, cyl=4, trans='auto(l4)', drv='f', cty=19, hwy=27, fl='r', category='midsize')
Pandas(Index=33, manufacturer='chevrolet', model='malibu', displ=2.4, year=2008, cyl=4, trans='auto(l4)', drv='f', cty=22, hwy=30, fl='r', category='midsize')
Pandas(Index=34, manufacturer='chevrolet', model='malibu', displ=3.1, year=1999, cyl=6, trans='auto(l4)', drv='f', cty=18, hwy=26, fl='r', category='midsize')
Pandas(Index=35, manufacturer='chevrolet', model='malibu', displ=3.5, year=2008, cyl=6, trans='auto(l4)', drv='f', cty=18, hwy=29, fl='r', category='midsize')
Pandas(Index=36, manufacturer='chevrolet', model='malibu', displ=3.6, year=2008, cyl=6, trans='auto(s6)', drv='f', cty=17, hwy=26, fl='r', category='midsize')
Pandas(Index=37, manufacturer='dodge', model='caravan 2wd', displ=2.4, year=1999, cyl=4, trans='auto(l3)', drv='f', cty=18, hwy=24, fl='r', category='minivan')
Pandas(Index=38, manufacturer='dodge', model='caravan 2wd', displ=3.0, year=1999, cyl=6, trans='auto(l4)', drv='f', cty=17, hwy=24, fl='r', category='minivan')
Pandas(Index=39, manufacturer='dodge', model='caravan 2wd', displ=3.3, year=1999, cyl=6, trans='auto(l4)', drv='f', cty=16, hwy=22, fl='r', category='minivan')
Pandas(Index=40, manufacturer='dodge', model='caravan 2wd', displ=3.3, year=1999, cyl=6, trans='auto(l4)', drv='f', cty=16, hwy=22, fl='r', category='minivan')
Pandas(Index=41, manufacturer='dodge', model='caravan 2wd', displ=3.3, year=2008, cyl=6, trans='auto(l4)', drv='f', cty=17, hwy=24, fl='r', category='minivan')
Pandas(Index=42, manufacturer='dodge', model='caravan 2wd', displ=3.3, year=2008, cyl=6, trans='auto(l4)', drv='f', cty=17, hwy=24, fl='r', category='minivan')
Pandas(Index=43, manufacturer='dodge', model='caravan 2wd', displ=3.3, year=2008, cyl=6, trans='auto(l4)', drv='f', cty=11, hwy=17, fl='e', category='minivan')
Pandas(Index=44, manufacturer='dodge', model='caravan 2wd', displ=3.8, year=1999, cyl=6, trans='auto(l4)', drv='f', cty=15, hwy=22, fl='r', category='minivan')
Pandas(Index=45, manufacturer='dodge', model='caravan 2wd', displ=3.8, year=1999, cyl=6, trans='auto(l4)', drv='f', cty=15, hwy=21, fl='r', category='minivan')
Pandas(Index=46, manufacturer='dodge', model='caravan 2wd', displ=3.8, year=2008, cyl=6, trans='auto(l6)', drv='f', cty=16, hwy=23, fl='r', category='minivan')
Pandas(Index=47, manufacturer='dodge', model='caravan 2wd', displ=4.0, year=2008, cyl=6, trans='auto(l6)', drv='f', cty=16, hwy=23, fl='r', category='minivan')
Pandas(Index=48, manufacturer='dodge', model='dakota pickup 4wd', displ=3.7, year=2008, cyl=6, trans='manual(m6)', drv='4', cty=15, hwy=19, fl='r', category='pickup')
Pandas(Index=49, manufacturer='dodge', model='dakota pickup 4wd', displ=3.7, year=2008, cyl=6, trans='auto(l4)', drv='4', cty=14, hwy=18, fl='r', category='pickup')
Pandas(Index=50, manufacturer='dodge', model='dakota pickup 4wd', displ=3.9, year=1999, cyl=6, trans='auto(l4)', drv='4', cty=13, hwy=17, fl='r', category='pickup')
Pandas(Index=51, manufacturer='dodge', model='dakota pickup 4wd', displ=3.9, year=1999, cyl=6, trans='manual(m5)', drv='4', cty=14, hwy=17, fl='r', category='pickup')
Pandas(Index=52, manufacturer='dodge', model='dakota pickup 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=14, hwy=19, fl='r', category='pickup')
Pandas(Index=53, manufacturer='dodge', model='dakota pickup 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=14, hwy=19, fl='r', category='pickup')
Pandas(Index=54, manufacturer='dodge', model='dakota pickup 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=9, hwy=12, fl='e', category='pickup')
Pandas(Index=55, manufacturer='dodge', model='dakota pickup 4wd', displ=5.2, year=1999, cyl=8, trans='manual(m5)', drv='4', cty=11, hwy=17, fl='r', category='pickup')
Pandas(Index=56, manufacturer='dodge', model='dakota pickup 4wd', displ=5.2, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=11, hwy=15, fl='r', category='pickup')
Pandas(Index=57, manufacturer='dodge', model='durango 4wd', displ=3.9, year=1999, cyl=6, trans='auto(l4)', drv='4', cty=13, hwy=17, fl='r', category='suv')
Pandas(Index=58, manufacturer='dodge', model='durango 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=13, hwy=17, fl='r', category='suv')
Pandas(Index=59, manufacturer='dodge', model='durango 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=9, hwy=12, fl='e', category='suv')
Pandas(Index=60, manufacturer='dodge', model='durango 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=13, hwy=17, fl='r', category='suv')
Pandas(Index=61, manufacturer='dodge', model='durango 4wd', displ=5.2, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=11, hwy=16, fl='r', category='suv')
Pandas(Index=62, manufacturer='dodge', model='durango 4wd', displ=5.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=13, hwy=18, fl='r', category='suv')
Pandas(Index=63, manufacturer='dodge', model='durango 4wd', displ=5.9, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=11, hwy=15, fl='r', category='suv')
Pandas(Index=64, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=4.7, year=2008, cyl=8, trans='manual(m6)', drv='4', cty=12, hwy=16, fl='r', category='pickup')
Pandas(Index=65, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=9, hwy=12, fl='e', category='pickup')
Pandas(Index=66, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=13, hwy=17, fl='r', category='pickup')
Pandas(Index=67, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=4.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=13, hwy=17, fl='r', category='pickup')
Pandas(Index=68, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=4.7, year=2008, cyl=8, trans='manual(m6)', drv='4', cty=12, hwy=16, fl='r', category='pickup')
Pandas(Index=69, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=4.7, year=2008, cyl=8, trans='manual(m6)', drv='4', cty=9, hwy=12, fl='e', category='pickup')
Pandas(Index=70, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=5.2, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=11, hwy=15, fl='r', category='pickup')
Pandas(Index=71, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=5.2, year=1999, cyl=8, trans='manual(m5)', drv='4', cty=11, hwy=16, fl='r', category='pickup')
Pandas(Index=72, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=5.7, year=2008, cyl=8, trans='auto(l5)', drv='4', cty=13, hwy=17, fl='r', category='pickup')
Pandas(Index=73, manufacturer='dodge', model='ram 1500 pickup 4wd', displ=5.9, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=11, hwy=15, fl='r', category='pickup')
Pandas(Index=74, manufacturer='ford', model='expedition 2wd', displ=4.6, year=1999, cyl=8, trans='auto(l4)', drv='r', cty=11, hwy=17, fl='r', category='suv')
Pandas(Index=75, manufacturer='ford', model='expedition 2wd', displ=5.4, year=1999, cyl=8, trans='auto(l4)', drv='r', cty=11, hwy=17, fl='r', category='suv')
Pandas(Index=76, manufacturer='ford', model='expedition 2wd', displ=5.4, year=2008, cyl=8, trans='auto(l6)', drv='r', cty=12, hwy=18, fl='r', category='suv')
Pandas(Index=77, manufacturer='ford', model='explorer 4wd', displ=4.0, year=1999, cyl=6, trans='auto(l5)', drv='4', cty=14, hwy=17, fl='r', category='suv')
Pandas(Index=78, manufacturer='ford', model='explorer 4wd', displ=4.0, year=1999, cyl=6, trans='manual(m5)', drv='4', cty=15, hwy=19, fl='r', category='suv')
Pandas(Index=79, manufacturer='ford', model='explorer 4wd', displ=4.0, year=1999, cyl=6, trans='auto(l5)', drv='4', cty=14, hwy=17, fl='r', category='suv')
Pandas(Index=80, manufacturer='ford', model='explorer 4wd', displ=4.0, year=2008, cyl=6, trans='auto(l5)', drv='4', cty=13, hwy=19, fl='r', category='suv')
Pandas(Index=81, manufacturer='ford', model='explorer 4wd', displ=4.6, year=2008, cyl=8, trans='auto(l6)', drv='4', cty=13, hwy=19, fl='r', category='suv')
Pandas(Index=82, manufacturer='ford', model='explorer 4wd', displ=5.0, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=13, hwy=17, fl='r', category='suv')
Pandas(Index=83, manufacturer='ford', model='f150 pickup 4wd', displ=4.2, year=1999, cyl=6, trans='auto(l4)', drv='4', cty=14, hwy=17, fl='r', category='pickup')
Pandas(Index=84, manufacturer='ford', model='f150 pickup 4wd', displ=4.2, year=1999, cyl=6, trans='manual(m5)', drv='4', cty=14, hwy=17, fl='r', category='pickup')
Pandas(Index=85, manufacturer='ford', model='f150 pickup 4wd', displ=4.6, year=1999, cyl=8, trans='manual(m5)', drv='4', cty=13, hwy=16, fl='r', category='pickup')
Pandas(Index=86, manufacturer='ford', model='f150 pickup 4wd', displ=4.6, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=13, hwy=16, fl='r', category='pickup')
Pandas(Index=87, manufacturer='ford', model='f150 pickup 4wd', displ=4.6, year=2008, cyl=8, trans='auto(l4)', drv='4', cty=13, hwy=17, fl='r', category='pickup')
Pandas(Index=88, manufacturer='ford', model='f150 pickup 4wd', displ=5.4, year=1999, cyl=8, trans='auto(l4)', drv='4', cty=11, hwy=15, fl='r', category='pickup')
Pandas(Index=89, manufacturer='ford', model='f150 pickup 4wd', displ=5.4, year=2008, cyl=8, trans='auto(l4)', drv='4', cty=13, hwy=17, fl='r', category='pickup')
Pandas(Index=90, manufacturer='ford', model='mustang', displ=3.8, year=1999, cyl=6, trans='manual(m5)', drv='r', cty=18, hwy=26, fl='r', category='subcompact')
Pandas(Index=91, manufacturer='ford', model='mustang', displ=3.8, year=1999, cyl=6, trans='auto(l4)', drv='r', cty=18, hwy=25, fl='r', category='subcompact')
Pandas(Index=92, manufacturer='ford', model='mustang', displ=4.0, year=2008, cyl=6, trans='manual(m5)', drv='r', cty=17, hwy=26, fl='r', category='subcompact')
Pandas(Index=93, manufacturer='ford', model='mustang', displ=4.0, year=2008, cyl=6, trans='auto(l5)', drv='r', cty=16, hwy=24, fl='r', category='subcompact')
Pandas(Index=94, manufacturer='ford', model='mustang', displ=4.6, year=1999, cyl=8, trans='auto(l4)', drv='r', cty=15, hwy=21, fl='r', category='subcompact')
Pandas(Index=95, manufacturer='ford', model='mustang', displ=4.6, year=1999, cyl=8, trans='manual(m5)', drv='r', cty=15, hwy=22, fl='r', category='subcompact')
Pandas(Index=96, manufacturer='ford', model='mustang', displ=4.6, year=2008, cyl=8, trans='manual(m5)', drv='r', cty=15, hwy=23, fl='r', category='subcompact')
Pandas(Index=97, manufacturer='ford', model='mustang', displ=4.6, year=2008, cyl=8, trans='auto(l5)', drv='r', cty=15, hwy=22, fl='r', category='subcompact')
Pandas(Index=98, manufacturer='ford', model='mustang', displ=5.4, year=2008, cyl=8, trans='manual(m6)', drv='r', cty=14, hwy=20, fl='p', category='subcompact')
Pandas(Index=99, manufacturer='honda', model='civic', displ=1.6, year=1999, cyl=4, trans='manual(m5)', drv='f', cty=28, hwy=33, fl='r', category='subcompact')
Pandas(Index=100, manufacturer='honda', model='civic', displ=1.6, year=1999, cyl=4, trans='auto(l4)', drv='f', cty=24, hwy=32, fl='r', category='subcompact')
Pandas(Index=101, manufacturer='honda', model='civic', displ=1.6, year=1999, cyl=4, trans='manual(m5)', drv='f', cty=25, hwy=32, fl='r', category='subcompact')
Pandas(Index=102, manufacturer='honda', model='civic', displ=1.6, year=1999, cyl=4, trans='manual(m5)', drv='f', cty=23, hwy=29, fl='p', category='subcompact')
Pandas(Index=103, manufacturer='honda', model='civic', displ=1.6, year=1999, cyl=4, trans='auto(l4)', drv='f', cty=24, hwy=32, fl='r', category='subcompact')
Pandas(Index=104, manufacturer='honda', model='civic', displ=1.8, year=2008, cyl=4, trans='manual(m5)', drv='f', cty=26, hwy=34, fl='r', category='subcompact')
Pandas(Index=105, manufacturer='honda', model='civic', displ=1.8, year=2008, cyl=4, trans='auto(l5)', drv='f', cty=25, hwy=36, fl='r', category='subcompact')
Pandas(Index=106, manufacturer='honda', model='civic', displ=1.8, year=2008, cyl=4, trans='auto(l5)', drv='f', cty=24, hwy=36, fl='c', category='subcompact')
Pandas(Index=107, manufacturer='honda', model='civic', displ=2.0, year=2008, cyl=4, trans='manual(m6)', drv='f', cty=21, hwy=29, fl='p', category='subcompact')
Pandas(Index=108, manufacturer='hyundai', model='sonata', displ=2.4, year=1999, cyl=4, trans='auto(l4)', drv='f', cty=18, hwy=26, fl='r', category='midsize')
Pandas(Index=109, manufacturer='hyundai', model='sonata', displ=2.4, year=1999, cyl=4, trans='manual(m5)', drv='f', cty=18, hwy=27, fl='r', category='midsize')
Pandas(Index=110, manufacturer='hyundai', model='sonata', displ=2.4, year=2008, cyl=4, trans='auto(l4)', drv='f', cty=21, hwy=30, fl='r', category='midsize')
Pandas(Index=111, manufacturer='hyundai', model='sonata', displ=2.4, year=2008, cyl=4, trans='manual(m5)', drv='f', cty=21, hwy=31, fl='r', category='midsize')
Pandas(Index=112, manufacturer='hyundai', model='sonata', displ=2.5, year=1999, cyl=6, trans='auto(l4)', drv='f', cty=18, hwy=26, fl='r', category='midsize')
Pandas(Index=113, manufacturer='hyundai', model='sonata', displ=2.5, year=1999, cyl=6, trans='manual(m5)', drv='f', cty=18, hwy=26, fl='r', category='midsize')
Pandas(Index=114, manufacturer='hyundai', model='sonata', displ=3.3, year=2008, cyl=6, trans='auto(l5)', drv='f', cty=19, hwy=28, fl='r', category='midsize')
Pandas(Index=115, manufacturer='hyundai', model='tiburon', displ=2.0, year=1999, cyl=4, trans='auto(l4)', drv='f', cty=19, hwy=26, fl='r', category='subcompact')
Pandas(Index=116, manufacturer='hyundai', model='tiburon', displ=2.0, year=1999, cyl=4, trans='manual(m5)', drv='f', cty=19, hwy=29, fl='r', category='subcompact')
Pandas(Index=117, manufacturer='hyundai', model='tiburon', displ=2.0, year=2008, cyl=4, trans='manual(m5)', drv='f', cty=20, hwy=28, fl='r', category='subcompact')
Pandas(Index=118, manufacturer='hyundai', model='tiburon', displ=2.0, year=2008, cyl=4, trans='auto(l4)', drv='f', cty=20, hwy=27, fl='r', category='subcompact')
Pandas(Index=119, manufacturer='hyundai', model='tiburon', displ=2.7, year=2008, cyl=6, trans='auto(l4)', drv='f', cty=17, hwy=24, fl='r', category='subcompact')
Pandas(Index=120, manufacturer='hyundai', model='tiburon', displ=2.7, year=2008, cyl=6, trans='manual(m6)', drv='f', cty=16, hwy=24, fl='r', category='subcompact')
Pandas(Index=121, manufacturer='hyundai', model='tiburon', displ=2.7, year=2008, cyl=6, trans='manual(m5)', drv='f', cty=17, hwy=24, fl='r', category='subcompact')
Pandas(Index=122, manufacturer='jeep', model='grand cherokee 4wd', displ=3.0, year=2008, cyl=6, trans='auto(l5)', drv='4', cty=17, hwy=22, fl='d', category='suv')
Pandas(Index=123, manufacturer='jeep', model='grand cherokee 4wd', displ=3.7, year=2008, cyl=6, trans='auto(l5)', drv='4', cty=15, hwy=19, fl='r', category='suv')

In [31]:
for row in mpg.itertuples():
    print(row.manufacturer, row.cty)

audi 18
audi 21
audi 20
audi 21
audi 16
audi 18
audi 18
audi 18
audi 16
audi 20
audi 19
audi 15
audi 17
audi 17
audi 15
audi 15
audi 17
audi 16
chevrolet 14
chevrolet 11
chevrolet 14
chevrolet 13
chevrolet 12
chevrolet 16
chevrolet 15
chevrolet 16
chevrolet 15
chevrolet 15
chevrolet 14
chevrolet 11
chevrolet 11
chevrolet 14
chevrolet 19
chevrolet 22
chevrolet 18
chevrolet 18
chevrolet 17
dodge 18
dodge 17
dodge 16
dodge 16
dodge 17
dodge 17
dodge 11
dodge 15
dodge 15
dodge 16
dodge 16
dodge 15
dodge 14
dodge 13
dodge 14
dodge 14
dodge 14
dodge 9
dodge 11
dodge 11
dodge 13
dodge 13
dodge 9
dodge 13
dodge 11
dodge 13
dodge 11
dodge 12
dodge 9
dodge 13
dodge 13
dodge 12
dodge 9
dodge 11
dodge 11
dodge 13
dodge 11
ford 11
ford 11
ford 12
ford 14
ford 15
ford 14
ford 13
ford 13
ford 13
ford 14
ford 14
ford 13
ford 13
ford 13
ford 11
ford 13
ford 18
ford 18
ford 17
ford 16
ford 15
ford 15
ford 15
ford 15
ford 14
honda 28
honda 24
honda 25
honda 23
honda 24
honda 26
honda 25
honda 24
honda 21
hyundai 18
hyundai 18
hyundai 21
hyundai 21
hyundai 18
hyundai 18
hyundai 19
hyundai 19
hyundai 19
hyundai 20
hyundai 20
hyundai 17
hyundai 16
hyundai 17
jeep 17
jeep 15
jeep 15
jeep 14
jeep 9
jeep 14
jeep 13
jeep 11
land rover 11
land rover 12
land rover 12
land rover 11
lincoln 11
lincoln 11
lincoln 12
mercury 14
mercury 13
mercury 13
mercury 13
nissan 21
nissan 19
nissan 23
nissan 23
nissan 19
nissan 19
nissan 18
nissan 19
nissan 19
nissan 14
nissan 15
nissan 14
nissan 12
pontiac 18
pontiac 16
pontiac 17
pontiac 18
pontiac 16
subaru 18
subaru 18
subaru 20
subaru 19
subaru 20
subaru 18
subaru 21
subaru 19
subaru 19
subaru 19
subaru 20
subaru 20
subaru 19
subaru 20
toyota 15
toyota 16
toyota 15
toyota 15
toyota 16
toyota 14
toyota 21
toyota 21
toyota 21
toyota 21
toyota 18
toyota 18
toyota 19
toyota 21
toyota 21
toyota 21
toyota 22
toyota 18
toyota 18
toyota 18
toyota 24
toyota 24
toyota 26
toyota 28
toyota 26
toyota 11
toyota 13
toyota 15
toyota 16
toyota 17
toyota 15
toyota 15
toyota 15
toyota 16
volkswagen 21
volkswagen 19
volkswagen 21
volkswagen 22
volkswagen 17
volkswagen 33
volkswagen 21
volkswagen 19
volkswagen 22
volkswagen 21
volkswagen 21
volkswagen 21
volkswagen 16
volkswagen 17
volkswagen 35
volkswagen 29
volkswagen 21
volkswagen 19
volkswagen 20
volkswagen 20
volkswagen 21
volkswagen 18
volkswagen 19
volkswagen 21
volkswagen 16
volkswagen 18
volkswagen 17

- 컬럼 기반 접근
- 컬럼의 데이터타입에 따라 출력

In [33]:
for col in mpg.columns:
    print(col)

manufacturer
model
displ
year
cyl
trans
drv
cty
hwy
fl
category

In [34]:
for col in mpg.columns:
    df_coltp = str(mpg[col].dtype)
    if df_coltp =='object':
        print(col,'object')
    else:
        print(col,'else')

manufacturer object
model object
displ else
year else
cyl else
trans object
drv object
cty else
hwy else
fl object
category object

In [35]:
for col in mpg.columns:
    df_coltp = str(mpg[col].dtype)
    if df_coltp =='object':
        print(col, mpg[col].value_counts()) #값의 통계
    else:
        print(col,mpg[col].describe())

manufacturer dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: manufacturer, dtype: int64
model caravan 2wd               11
ram 1500 pickup 4wd       10
civic                      9
jetta                      9
dakota pickup 4wd          9
mustang                    9
impreza awd                8
a4 quattro                 8
grand cherokee 4wd         8
a4                         7
toyota tacoma 4wd          7
camry solara               7
camry                      7
tiburon                    7
sonata                     7
passat                     7
f150 pickup 4wd            7
durango 4wd                7
explorer 4wd               6
new beetle                 6
altima                     6
4runner 4wd                6
forester awd               6
gti                        5
c1500 suburban 2wd         5
corolla                    5
corvette                   5
malibu                     5
grand prix                 5
k1500 tahoe 4wd            4
pathfinder 4wd             4
mountaineer 4wd            4
range rover                4
maxima                     3
navigator 2wd              3
a6 quattro                 3
expedition 2wd             3
land cruiser wagon 4wd     2
Name: model, dtype: int64
displ count    234.000000
mean       3.471795
std        1.291959
min        1.600000
25%        2.400000
50%        3.300000
75%        4.600000
max        7.000000
Name: displ, dtype: float64
year count     234.000000
mean     2003.500000
std         4.509646
min      1999.000000
25%      1999.000000
50%      2003.500000
75%      2008.000000
max      2008.000000
Name: year, dtype: float64
cyl count    234.000000
mean       5.888889
std        1.611534
min        4.000000
25%        4.000000
50%        6.000000
75%        8.000000
max        8.000000
Name: cyl, dtype: float64
trans auto(l4)      83
manual(m5)    58
auto(l5)      39
manual(m6)    19
auto(s6)      16
auto(l6)       6
auto(av)       5
auto(s5)       3
auto(s4)       3
auto(l3)       2
Name: trans, dtype: int64
drv f    106
4    103
r     25
Name: drv, dtype: int64
cty count    234.000000
mean      16.858974
std        4.255946
min        9.000000
25%       14.000000
50%       17.000000
75%       19.000000
max       35.000000
Name: cty, dtype: float64
hwy count    234.000000
mean      23.440171
std        5.954643
min       12.000000
25%       18.000000
50%       24.000000
75%       27.000000
max       44.000000
Name: hwy, dtype: float64
fl r    168
p     52
e      8
d      5
c      1
Name: fl, dtype: int64
category suv           62
compact       47
midsize       41
subcompact    35
pickup        33
minivan       11
2seater        5
Name: category, dtype: int64

- 시리즈 형태로 반복문 이용하여 조건문

In [36]:
#mpg 데이터 중 trans 변수에 m5 값이 있는 데이터를 출력하여 제조사별 카운팅
def get_trans_spe(series):
    tr_cnt =len([ _ for x in series if x[0] in 'm5'])
    return tr_cnt

In [38]:
#제조사 별로 카운팅
mpg.groupby('manufacturer').agg({'trans':get_trans_spe}).reset_index()

   manufacturer  trans
0          audi      7
1     chevrolet      3
2         dodge      7
3          ford      8
4         honda      5
5       hyundai      7
6          jeep      0
7    land rover      0
8       lincoln      0
9       mercury      0
10       nissan      5
11      pontiac      0
12       subaru      7
13       toyota     14
14   volkswagen     14

In [39]:
#cty평균 조건으로 데이터 묶기
def get_y_cty(series):
    if mpg.iloc[series.index[0], : ]['year'] == 2008:
        cty_cnt = len([_ for x in series if x>=16]) #cty평균 16 이상
    else:
        cty_cnt = len([_ for x in series if x<16]) #cty평균 16 미만
    return cty_cnt

In [40]:
#연도별로 묶기
mpg.groupby('year').agg({'cty':get_y_cty}).reset_index()

   year  cty
0  1999   48
1  2008   68

### 데이터 나누기

- cut 함수